export type ContentLocale = { hi: string; es: string; ja: string };

export type SentenceChunkBlueprint = {
  chinese: string;
  pinyin: string;
  meaning: string;
};

export type UtteranceBlueprint = {
  chinese: string;
  pinyin: string;
  english: string;
  localized: ContentLocale;
  chunks: SentenceChunkBlueprint[];
};

export type PatternKey =
  | 'pronunciation'
  | 'identity'
  | 'quantity'
  | 'time'
  | 'description'
  | 'possession'
  | 'location'
  | 'action'
  | 'preference'
  | 'request'
  | 'comparison'
  | 'social'
  | 'plan'
  | 'service'
  | 'grammar'
  | 'opinion'
  | 'formal'
  | 'reading'
  | 'narrative'
  | 'fluency';

export type TopicBlueprint = {
  courseSlug: string;
  patternKey: PatternKey;
  primary: UtteranceBlueprint;
  response: UtteranceBlueprint;
};

const localized = (english: string, hi: string, es?: string, ja?: string): ContentLocale => ({
  hi,
  es: es || english,
  ja: ja || english,
});

const U = (
  chineseChunks: string,
  pinyinChunks: string,
  meaningChunks: string,
  english: string,
  hi: string,
  es?: string,
  ja?: string
): UtteranceBlueprint => {
  const chinese = chineseChunks.split('|');
  const pinyin = pinyinChunks.split('|');
  const meanings = meaningChunks.split('|');
  if (chinese.length !== pinyin.length || chinese.length !== meanings.length) {
    throw new Error(`Invalid sentence breakdown for: ${chineseChunks}`);
  }
  return {
    chinese: chinese.join(''),
    pinyin: pinyin.join(' '),
    english,
    localized: localized(english, hi, es, ja),
    chunks: chinese.map((item, index) => ({ chinese: item, pinyin: pinyin[index], meaning: meanings[index] })),
  };
};

const T = (
  courseSlug: string,
  patternKey: PatternKey,
  primary: UtteranceBlueprint,
  response: UtteranceBlueprint
): TopicBlueprint => ({ courseSlug, patternKey, primary, response });

// Each topic has an original, practical exchange. Pipe separators mark teachable chunks;
// they are removed from the displayed sentence and become the word-by-word explanation.
export const TOPIC_BLUEPRINTS: TopicBlueprint[] = [
  T('pinyin-and-tones', 'pronunciation',
    U('妈妈|骑|马。', 'Māma|qí|mǎ.', 'mother|rides|a horse', 'Mother rides a horse.', 'माँ घोड़े की सवारी करती हैं।'),
    U('我能|听出|两个不同的声调。', 'Wǒ néng|tīngchū|liǎng ge bùtóng de shēngdiào.', 'I can|hear and distinguish|two different tones', 'I can hear the two different tones.', 'मैं दोनों अलग स्वरों को पहचान सकता/सकती हूँ।')),
  T('tone-change-rules', 'pronunciation',
    U('你好，|我|很好。', 'Ní hǎo,|wǒ|hěn hǎo.', 'hello|I|am very well', 'Hello, I am very well.', 'नमस्ते, मैं बहुत अच्छा/अच्छी हूँ।'),
    U('“一”和“不”|在口语里|会变调。', '“Yī” hé “bù”|zài kǒuyǔ lǐ|huì biàndiào.', '“one” and “not”|in spoken language|change tone', '“Yī” and “bù” change tone in natural speech.', 'बोलचाल में “一” और “不” का स्वर बदलता है।')),
  T('hello-and-greetings', 'social',
    U('你好，|很高兴|认识你。', 'Nǐ hǎo,|hěn gāoxìng|rènshi nǐ.', 'hello|very happy|to meet you', 'Hello, nice to meet you.', 'नमस्ते, आपसे मिलकर खुशी हुई।'),
    U('我也|很高兴|认识你。', 'Wǒ yě|hěn gāoxìng|rènshi nǐ.', 'I also|am very happy|to meet you', 'Nice to meet you too.', 'मुझे भी आपसे मिलकर खुशी हुई।')),
  T('introducing-yourself', 'identity',
    U('我叫|安娜，|来自|印度。', 'Wǒ jiào|Ānnà,|láizì|Yìndù.', 'I am called|Anna|come from|India', 'My name is Anna, and I am from India.', 'मेरा नाम अन्ना है और मैं भारत से हूँ।'),
    U('我是|中文|初学者。', 'Wǒ shì|Zhōngwén|chūxuézhě.', 'I am|Chinese language|a beginner', 'I am a beginner in Chinese.', 'मैं चीनी भाषा में शुरुआती विद्यार्थी हूँ।')),
  T('numbers-0-to-100', 'quantity',
    U('我们班|有|二十八个|学生。', 'Wǒmen bān|yǒu|èrshíbā ge|xuésheng.', 'our class|has|twenty-eight|students', 'There are twenty-eight students in our class.', 'हमारी कक्षा में अट्ठाईस विद्यार्थी हैं।'),
    U('今天|来了|二十五个人。', 'Jīntiān|lái le|èrshíwǔ ge rén.', 'today|came|twenty-five people', 'Twenty-five people came today.', 'आज पच्चीस लोग आए।')),
  T('numbers-100-to-10000', 'quantity',
    U('这台电脑|卖|三千六百元。', 'Zhè tái diànnǎo|mài|sānqiān liùbǎi yuán.', 'this computer|sells for|3,600 yuan', 'This computer costs 3,600 yuan.', 'इस कंप्यूटर की कीमत 3,600 युआन है।'),
    U('我的预算|只有|三千元。', 'Wǒ de yùsuàn|zhǐyǒu|sānqiān yuán.', 'my budget|is only|3,000 yuan', 'My budget is only 3,000 yuan.', 'मेरा बजट केवल 3,000 युआन है।')),
  T('time-and-clock', 'time',
    U('我|早上七点|起床。', 'Wǒ|zǎoshang qī diǎn|qǐchuáng.', 'I|at 7 a.m.|get up', 'I get up at seven in the morning.', 'मैं सुबह सात बजे उठता/उठती हूँ।'),
    U('八点半|开始|上课。', 'Bā diǎn bàn|kāishǐ|shàngkè.', 'at 8:30|start|class', 'Class starts at eight thirty.', 'कक्षा साढ़े आठ बजे शुरू होती है।')),
  T('days-and-dates', 'time',
    U('我们的会议|在|星期三下午。', 'Wǒmen de huìyì|zài|xīngqīsān xiàwǔ.', 'our meeting|is on|Wednesday afternoon', 'Our meeting is on Wednesday afternoon.', 'हमारी बैठक बुधवार दोपहर को है।'),
    U('请把日期|改到|五月十二号。', 'Qǐng bǎ rìqī|gǎi dào|wǔ yuè shí’èr hào.', 'please move the date|to|May 12', 'Please move the date to May 12.', 'कृपया तारीख 12 मई कर दें।')),
  T('months-and-seasons', 'time',
    U('北京的秋天|从九月|开始。', 'Běijīng de qiūtiān|cóng jiǔ yuè|kāishǐ.', 'Beijing autumn|from September|begins', 'Autumn in Beijing begins in September.', 'बीजिंग में पतझड़ सितंबर से शुरू होता है।'),
    U('我最喜欢|春天，|因为很暖和。', 'Wǒ zuì xǐhuan|chūntiān,|yīnwèi hěn nuǎnhuo.', 'I like most|spring|because it is warm', 'I like spring most because it is warm.', 'मुझे वसंत सबसे पसंद है क्योंकि मौसम गर्म रहता है।')),
  T('money-and-prices', 'service',
    U('这个|多少钱？', 'Zhège|duōshao qián?', 'this|how much money', 'How much is this?', 'यह कितने का है?'),
    U('一共|八十五块，|可以刷卡。', 'Yígòng|bāshíwǔ kuài,|kěyǐ shuākǎ.', 'in total|85 yuan|you may pay by card', 'It is 85 yuan in total; you can pay by card.', 'कुल 85 युआन हैं; आप कार्ड से भुगतान कर सकते हैं।')),
  T('colors-and-shapes', 'description',
    U('我想要|那只|圆圆的蓝色杯子。', 'Wǒ xiǎng yào|nà zhī|yuányuán de lánsè bēizi.', 'I want|that one|round blue cup', 'I want that round blue cup.', 'मुझे वह गोल नीला कप चाहिए।'),
    U('旁边的|方形盒子|也是蓝色的。', 'Pángbiān de|fāngxíng hézi|yě shì lánsè de.', 'the nearby|square box|is also blue', 'The square box next to it is blue too.', 'पास वाला चौकोर डिब्बा भी नीला है।')),
  T('sizes-and-measurements', 'comparison',
    U('这张桌子|长|一米二。', 'Zhè zhāng zhuōzi|cháng|yì mǐ èr.', 'this table|is long|1.2 metres', 'This table is 1.2 metres long.', 'यह मेज़ 1.2 मीटर लंबी है।'),
    U('那张桌子|比这张|宽一点儿。', 'Nà zhāng zhuōzi|bǐ zhè zhāng|kuān yìdiǎnr.', 'that table|compared with this one|is a little wider', 'That table is a little wider than this one.', 'वह मेज़ इससे थोड़ी चौड़ी है।')),
  T('family-members', 'possession',
    U('我家|有|五口人。', 'Wǒ jiā|yǒu|wǔ kǒu rén.', 'my family|has|five members', 'There are five people in my family.', 'मेरे परिवार में पाँच लोग हैं।'),
    U('我姐姐|比我|大三岁。', 'Wǒ jiějie|bǐ wǒ|dà sān suì.', 'my older sister|than me|is three years older', 'My older sister is three years older than me.', 'मेरी बड़ी बहन मुझसे तीन साल बड़ी है।')),
  T('my-home', 'location',
    U('我的房间|在|二楼左边。', 'Wǒ de fángjiān|zài|èr lóu zuǒbian.', 'my room|is|on the left upstairs', 'My room is on the left side of the second floor.', 'मेरा कमरा दूसरी मंज़िल पर बाईं ओर है।'),
    U('书桌旁边|有|一扇大窗户。', 'Shūzhuō pángbiān|yǒu|yí shàn dà chuānghu.', 'next to the desk|there is|a large window', 'There is a large window next to the desk.', 'मेज़ के पास एक बड़ी खिड़की है।')),
  T('daily-routine', 'action',
    U('我每天|先刷牙，|再吃早饭。', 'Wǒ měitiān|xiān shuāyá,|zài chī zǎofàn.', 'every day I|first brush my teeth|then eat breakfast', 'Every day I brush my teeth before breakfast.', 'मैं रोज़ पहले दाँत साफ करता/करती हूँ, फिर नाश्ता करता/करती हूँ।'),
    U('晚上十一点以前|我会|睡觉。', 'Wǎnshang shíyī diǎn yǐqián|wǒ huì|shuìjiào.', 'before 11 p.m.|I will|sleep', 'I go to sleep before eleven at night.', 'मैं रात ग्यारह बजे से पहले सो जाता/जाती हूँ।')),
  T('common-objects', 'possession',
    U('桌上|放着|一本词典和两支笔。', 'Zhuō shàng|fàngzhe|yì běn cídiǎn hé liǎng zhī bǐ.', 'on the table|are placed|a dictionary and two pens', 'A dictionary and two pens are on the table.', 'मेज़ पर एक शब्दकोश और दो पेन रखे हैं।'),
    U('那把钥匙|不是我的，|是你的。', 'Nà bǎ yàoshi|bú shì wǒ de,|shì nǐ de.', 'that key|is not mine|is yours', 'That key is not mine; it is yours.', 'वह चाबी मेरी नहीं, आपकी है।')),
  T('body-parts', 'description',
    U('我的左手|有一点儿|疼。', 'Wǒ de zuǒshǒu|yǒu yìdiǎnr|téng.', 'my left hand|a little|hurts', 'My left hand hurts a little.', 'मेरे बाएँ हाथ में थोड़ा दर्द है।'),
    U('请抬起|右胳膊，|慢慢转动。', 'Qǐng táiqǐ|yòu gēbo,|mànmàn zhuàndòng.', 'please raise|your right arm|turn slowly', 'Raise your right arm and rotate it slowly.', 'कृपया दायाँ हाथ उठाकर धीरे-धीरे घुमाएँ।')),
  T('feelings-and-emotions', 'description',
    U('听到这个消息，|我|特别开心。', 'Tīngdào zhège xiāoxi,|wǒ|tèbié kāixīn.', 'after hearing this news|I|am especially happy', 'I am very happy to hear this news.', 'यह खबर सुनकर मैं बहुत खुश हूँ।'),
    U('别担心，|我们会|一起解决。', 'Bié dānxīn,|wǒmen huì|yìqǐ jiějué.', 'do not worry|we will|solve it together', 'Do not worry; we will solve it together.', 'चिंता मत करो, हम इसे साथ मिलकर हल करेंगे।')),
  T('weather-and-nature', 'description',
    U('今天|多云，|下午可能下雨。', 'Jīntiān|duōyún,|xiàwǔ kěnéng xiàyǔ.', 'today|is cloudy|it may rain in the afternoon', 'It is cloudy today and may rain this afternoon.', 'आज बादल हैं और दोपहर में बारिश हो सकती है।'),
    U('出门以前|记得|带雨伞。', 'Chūmén yǐqián|jìde|dài yǔsǎn.', 'before going out|remember|to take an umbrella', 'Remember to take an umbrella before going out.', 'बाहर जाने से पहले छाता लेना याद रखना।')),
  T('review-foundations', 'grammar',
    U('我叫李明，|家里有三口人，|每天八点上班。', 'Wǒ jiào Lǐ Míng,|jiālǐ yǒu sān kǒu rén,|měitiān bā diǎn shàngbān.', 'my name is Li Ming|my family has three people|I work at eight every day', 'My name is Li Ming; there are three people in my family, and I start work at eight.', 'मेरा नाम ली मिंग है; परिवार में तीन लोग हैं और मैं रोज़ आठ बजे काम शुरू करता हूँ।'),
    U('今天星期五，|天气很好，|我们一起出去吧。', 'Jīntiān xīngqīwǔ,|tiānqì hěn hǎo,|wǒmen yìqǐ chūqù ba.', 'today is Friday|the weather is good|let us go out together', 'It is Friday and the weather is nice, so let us go out together.', 'आज शुक्रवार है और मौसम अच्छा है, इसलिए चलो साथ बाहर चलते हैं।')),
  T('food-basics', 'preference',
    U('我早饭|常吃|鸡蛋和面包。', 'Wǒ zǎofàn|cháng chī|jīdàn hé miànbāo.', 'for breakfast I|often eat|eggs and bread', 'I often eat eggs and bread for breakfast.', 'मैं नाश्ते में अक्सर अंडा और ब्रेड खाता/खाती हूँ।'),
    U('今天中午|我们吃|米饭和蔬菜。', 'Jīntiān zhōngwǔ|wǒmen chī|mǐfàn hé shūcài.', 'at noon today|we eat|rice and vegetables', 'We are having rice and vegetables for lunch.', 'आज दोपहर हम चावल और सब्ज़ियाँ खाएँगे।')),
  T('fruits-and-vegetables', 'preference',
    U('我最喜欢|苹果，|也常买香蕉。', 'Wǒ zuì xǐhuan|píngguǒ,|yě cháng mǎi xiāngjiāo.', 'I like most|apples|also often buy bananas', 'I like apples most, and I often buy bananas too.', 'मुझे सेब सबसे पसंद हैं और मैं अक्सर केले भी खरीदता/खरीदती हूँ।'),
    U('这些西红柿|很新鲜，|给我两斤吧。', 'Zhèxiē xīhóngshì|hěn xīnxiān,|gěi wǒ liǎng jīn ba.', 'these tomatoes|are fresh|give me one kilogram', 'These tomatoes are fresh; give me one kilogram.', 'ये टमाटर ताज़े हैं; मुझे एक किलो दे दीजिए।')),
  T('drinks-and-beverages', 'request',
    U('我想要|一杯热茶，|不要糖。', 'Wǒ xiǎng yào|yì bēi rè chá,|bú yào táng.', 'I would like|a cup of hot tea|do not want sugar', 'I would like a cup of hot tea without sugar.', 'मुझे बिना चीनी की एक कप गर्म चाय चाहिए।'),
    U('好的，|还需要|别的吗？', 'Hǎo de,|hái xūyào|bié de ma?', 'okay|still need|anything else', 'Okay. Would you like anything else?', 'ठीक है, क्या आपको कुछ और चाहिए?')),
  T('meat-and-seafood', 'preference',
    U('我不吃牛肉，|但是|可以吃鱼。', 'Wǒ bù chī niúròu,|dànshì|kěyǐ chī yú.', 'I do not eat beef|but|can eat fish', 'I do not eat beef, but I can eat fish.', 'मैं बीफ़ नहीं खाता/खाती, लेकिन मछली खा सकता/सकती हूँ।'),
    U('这道菜|里面|没有猪肉。', 'Zhè dào cài|lǐmiàn|méiyǒu zhūròu.', 'this dish|inside|has no pork', 'This dish does not contain pork.', 'इस व्यंजन में पोर्क नहीं है।')),
  T('ordering-food', 'service',
    U('服务员，|请给我们|一份菜单。', 'Fúwùyuán,|qǐng gěi wǒmen|yí fèn càidān.', 'waiter|please give us|a menu', 'Excuse me, please bring us a menu.', 'वेटर, कृपया हमें एक मेन्यू दीजिए।'),
    U('我要|一碗牛肉面，|少放辣椒。', 'Wǒ yào|yì wǎn niúròu miàn,|shǎo fàng làjiāo.', 'I want|a bowl of beef noodles|use less chilli', 'I would like beef noodles with less chilli.', 'मुझे कम मिर्च वाले बीफ़ नूडल्स चाहिए।')),
  T('cooking-verbs', 'action',
    U('先把土豆|切成小块，|再放进锅里。', 'Xiān bǎ tǔdòu|qiē chéng xiǎo kuài,|zài fàng jìn guō lǐ.', 'first take the potatoes|cut into small pieces|then put into the pot', 'First cut the potatoes into small pieces, then put them in the pot.', 'पहले आलू छोटे टुकड़ों में काटें, फिर बर्तन में डालें।'),
    U('水开以后|煮|十分钟。', 'Shuǐ kāi yǐhòu|zhǔ|shí fēnzhōng.', 'after the water boils|cook|for ten minutes', 'Cook it for ten minutes after the water boils.', 'पानी उबलने के बाद दस मिनट पकाएँ।')),
  T('tastes-and-flavors', 'description',
    U('这个汤|有点儿咸，|但味道很鲜。', 'Zhège tāng|yǒudiǎnr xián,|dàn wèidào hěn xiān.', 'this soup|is a little salty|but tastes savoury', 'This soup is a little salty, but very savoury.', 'यह सूप थोड़ा नमकीन है, लेकिन स्वाद बहुत अच्छा है।'),
    U('我喜欢|酸甜的味道，|不太能吃辣。', 'Wǒ xǐhuan|suāntián de wèidào,|bú tài néng chī là.', 'I like|sweet-and-sour flavour|cannot eat much spice', 'I like sweet-and-sour flavours and cannot eat very spicy food.', 'मुझे खट्टा-मीठा स्वाद पसंद है और बहुत तीखा नहीं खा सकता/सकती।')),
  T('pets', 'possession',
    U('我养了|一只小猫，|它叫豆豆。', 'Wǒ yǎng le|yì zhī xiǎomāo,|tā jiào Dòudou.', 'I keep|a kitten|it is called Doudou', 'I have a kitten named Doudou.', 'मेरे पास एक बिल्ली का बच्चा है जिसका नाम दोउदोउ है।'),
    U('它每天|喜欢在窗边|晒太阳。', 'Tā měitiān|xǐhuan zài chuāngbiān|shài tàiyáng.', 'every day it|likes by the window|to bask in the sun', 'It likes to sit by the window in the sun every day.', 'उसे रोज़ खिड़की के पास धूप सेंकना पसंद है।')),
  T('wild-animals', 'description',
    U('大熊猫|主要生活在|中国的竹林里。', 'Dàxióngmāo|zhǔyào shēnghuó zài|Zhōngguó de zhúlín lǐ.', 'giant pandas|mainly live in|China’s bamboo forests', 'Giant pandas mainly live in China’s bamboo forests.', 'विशाल पांडा मुख्य रूप से चीन के बाँस के जंगलों में रहते हैं।'),
    U('野生动物|需要|安全的生活环境。', 'Yěshēng dòngwù|xūyào|ānquán de shēnghuó huánjìng.', 'wild animals|need|a safe habitat', 'Wild animals need a safe habitat.', 'जंगली जानवरों को सुरक्षित आवास चाहिए।')),
  T('farm-animals', 'description',
    U('农场里|养着|牛、羊和鸡。', 'Nóngchǎng lǐ|yǎngzhe|niú, yáng hé jī.', 'on the farm|are raised|cows sheep and chickens', 'Cows, sheep and chickens are raised on the farm.', 'खेत में गाय, भेड़ और मुर्गियाँ पाली जाती हैं।'),
    U('每天早上|农夫都会|给它们喂食。', 'Měitiān zǎoshang|nóngfū dōu huì|gěi tāmen wèishí.', 'every morning|the farmer will|feed them', 'The farmer feeds them every morning.', 'किसान हर सुबह उन्हें खाना खिलाता है।')),
  T('plants-and-trees', 'description',
    U('这棵树|春天开花，|秋天结果。', 'Zhè kē shù|chūntiān kāihuā,|qiūtiān jiēguǒ.', 'this tree|flowers in spring|bears fruit in autumn', 'This tree flowers in spring and bears fruit in autumn.', 'यह पेड़ वसंत में फूल देता है और पतझड़ में फल।'),
    U('植物生长|需要|阳光和水。', 'Zhíwù shēngzhǎng|xūyào|yángguāng hé shuǐ.', 'plant growth|needs|sunlight and water', 'Plants need sunlight and water to grow.', 'पौधों को बढ़ने के लिए धूप और पानी चाहिए।')),
  T('land-and-water', 'location',
    U('这条河|从山里|流向大海。', 'Zhè tiáo hé|cóng shān lǐ|liú xiàng dàhǎi.', 'this river|from the mountains|flows toward the sea', 'This river flows from the mountains to the sea.', 'यह नदी पहाड़ों से समुद्र की ओर बहती है।'),
    U('湖的北边|有|一片森林。', 'Hú de běibian|yǒu|yí piàn sēnlín.', 'north of the lake|there is|a forest', 'There is a forest north of the lake.', 'झील के उत्तर में एक जंगल है।')),
  T('clothing-basics', 'description',
    U('今天很冷，|你应该穿|一件厚外套。', 'Jīntiān hěn lěng,|nǐ yīnggāi chuān|yí jiàn hòu wàitào.', 'today is cold|you should wear|a thick coat', 'It is cold today; you should wear a thick coat.', 'आज ठंड है, आपको मोटा कोट पहनना चाहिए।'),
    U('这条裤子|颜色合适，|但是有点儿长。', 'Zhè tiáo kùzi|yánsè héshì,|dànshì yǒudiǎnr cháng.', 'these trousers|have a suitable colour|but are a little long', 'The colour of these trousers works, but they are a little long.', 'इस पैंट का रंग ठीक है, लेकिन यह थोड़ी लंबी है।')),
  T('accessories', 'description',
    U('这块手表|跟你的包|很相配。', 'Zhè kuài shǒubiǎo|gēn nǐ de bāo|hěn xiāngpèi.', 'this watch|with your bag|matches well', 'This watch matches your bag very well.', 'यह घड़ी आपके बैग से बहुत अच्छी तरह मेल खाती है।'),
    U('我的眼镜|放在|黑色盒子里。', 'Wǒ de yǎnjìng|fàng zài|hēisè hézi lǐ.', 'my glasses|are placed|inside the black case', 'My glasses are in the black case.', 'मेरा चश्मा काले डिब्बे में रखा है।')),
  T('shopping-phrases', 'service',
    U('这件衬衫|有|大一点儿的吗？', 'Zhè jiàn chènshān|yǒu|dà yìdiǎnr de ma?', 'this shirt|is there|a larger one', 'Do you have this shirt in a larger size?', 'क्या यह शर्ट एक बड़े साइज़ में है?'),
    U('有，|您可以|先试穿一下。', 'Yǒu,|nín kěyǐ|xiān shìchuān yíxià.', 'yes|you may|try it on first', 'Yes, you may try it on first.', 'हाँ, आप पहले इसे पहनकर देख सकते हैं।')),
  T('land-transport', 'service',
    U('去市中心|坐几路|公共汽车？', 'Qù shì zhōngxīn|zuò jǐ lù|gōnggòng qìchē?', 'to go downtown|take which route|bus', 'Which bus goes to the city centre?', 'शहर के केंद्र जाने के लिए कौन-सी बस लें?'),
    U('坐十二路，|在第五站|下车。', 'Zuò shí’èr lù,|zài dì wǔ zhàn|xiàchē.', 'take route 12|at the fifth stop|get off', 'Take bus 12 and get off at the fifth stop.', 'बस 12 लें और पाँचवें स्टॉप पर उतरें।')),
  T('air-and-rail', 'service',
    U('我的火车|下午三点|从二号站台出发。', 'Wǒ de huǒchē|xiàwǔ sān diǎn|cóng èr hào zhàntái chūfā.', 'my train|at 3 p.m.|departs from platform 2', 'My train leaves from platform 2 at three this afternoon.', 'मेरी ट्रेन आज दोपहर तीन बजे प्लेटफॉर्म 2 से चलेगी।'),
    U('请提前|三十分钟|到车站。', 'Qǐng tíqián|sānshí fēnzhōng|dào chēzhàn.', 'please arrive early|by thirty minutes|at the station', 'Please arrive at the station thirty minutes early.', 'कृपया स्टेशन तीस मिनट पहले पहुँचें।')),
  T('directions', 'location',
    U('请问，|最近的地铁站|怎么走？', 'Qǐngwèn,|zuìjìn de dìtiě zhàn|zěnme zǒu?', 'excuse me|the nearest subway station|how to go', 'Excuse me, how do I get to the nearest subway station?', 'माफ़ कीजिए, सबसे नज़दीकी मेट्रो स्टेशन कैसे जाएँ?'),
    U('一直往前走，|到路口|右转。', 'Yìzhí wǎng qián zǒu,|dào lùkǒu|yòu zhuǎn.', 'go straight ahead|at the intersection|turn right', 'Go straight ahead and turn right at the intersection.', 'सीधे जाएँ और चौराहे पर दाएँ मुड़ें।')),
  T('places-in-city', 'location',
    U('银行|在邮局和药店|中间。', 'Yínháng|zài yóujú hé yàodiàn|zhōngjiān.', 'the bank|is between the post office and pharmacy|in the middle', 'The bank is between the post office and the pharmacy.', 'बैंक डाकघर और दवा की दुकान के बीच है।'),
    U('图书馆对面|有|一家咖啡馆。', 'Túshūguǎn duìmiàn|yǒu|yì jiā kāfēiguǎn.', 'opposite the library|there is|a café', 'There is a café opposite the library.', 'पुस्तकालय के सामने एक कैफ़े है।')),
  T('review-essentials', 'grammar',
    U('我坐地铁去市场，|买了水果，|还试穿了一件外套。', 'Wǒ zuò dìtiě qù shìchǎng,|mǎi le shuǐguǒ,|hái shìchuān le yí jiàn wàitào.', 'I took the subway to the market|bought fruit|also tried on a coat', 'I took the subway to the market, bought fruit and tried on a coat.', 'मैं मेट्रो से बाज़ार गया/गई, फल खरीदे और एक कोट पहनकर देखा।'),
    U('回家以前，|我在餐厅|点了一碗面。', 'Huí jiā yǐqián,|wǒ zài cāntīng|diǎn le yì wǎn miàn.', 'before returning home|at a restaurant I|ordered a bowl of noodles', 'Before going home, I ordered a bowl of noodles at a restaurant.', 'घर लौटने से पहले मैंने रेस्तरां में एक कटोरा नूडल्स मँगाया।')),
  T('making-friends', 'social',
    U('你平时|喜欢做什么？', 'Nǐ píngshí|xǐhuan zuò shénme?', 'usually you|like to do what', 'What do you usually like to do?', 'आप आम तौर पर क्या करना पसंद करते हैं?'),
    U('我喜欢摄影，|周末常去|公园拍照。', 'Wǒ xǐhuan shèyǐng,|zhōumò cháng qù|gōngyuán pāizhào.', 'I like photography|on weekends often go|take photos in the park', 'I like photography and often take pictures in the park on weekends.', 'मुझे फ़ोटोग्राफ़ी पसंद है और सप्ताहांत में पार्क में तस्वीरें लेता/लेती हूँ।')),
  T('hobbies-and-interests', 'preference',
    U('学中文以外，|我还对|做饭感兴趣。', 'Xué Zhōngwén yǐwài,|wǒ hái duì|zuòfàn gǎn xìngqù.', 'besides learning Chinese|I am also in|interested in cooking', 'Besides Chinese, I am also interested in cooking.', 'चीनी सीखने के अलावा मुझे खाना बनाने में भी रुचि है।'),
    U('我们可以|互相分享|学习经验。', 'Wǒmen kěyǐ|hùxiāng fēnxiǎng|xuéxí jīngyàn.', 'we can|share with each other|learning experience', 'We can share our learning experiences.', 'हम अपने सीखने के अनुभव एक-दूसरे से साझा कर सकते हैं।')),
  T('sports-and-exercise', 'action',
    U('我每周|跑步三次，|每次半小时。', 'Wǒ měi zhōu|pǎobù sān cì,|měi cì bàn xiǎoshí.', 'every week I|run three times|half an hour each time', 'I run three times a week for half an hour each time.', 'मैं सप्ताह में तीन बार, हर बार आधा घंटा दौड़ता/दौड़ती हूँ।'),
    U('运动以后|别忘了|喝水和拉伸。', 'Yùndòng yǐhòu|bié wàng le|hē shuǐ hé lāshēn.', 'after exercise|do not forget|drink water and stretch', 'Do not forget to drink water and stretch after exercise.', 'व्यायाम के बाद पानी पीना और स्ट्रेच करना न भूलें।')),
  T('music-and-movies', 'opinion',
    U('这部电影|故事很简单，|但是音乐特别好听。', 'Zhè bù diànyǐng|gùshi hěn jiǎndān,|dànshì yīnyuè tèbié hǎotīng.', 'this film|has a simple story|but beautiful music', 'The story is simple, but the film’s music is excellent.', 'इस फ़िल्म की कहानी सरल है, लेकिन संगीत बहुत अच्छा है।'),
    U('我最喜欢的歌手|下个月|要开演唱会。', 'Wǒ zuì xǐhuan de gēshǒu|xià ge yuè|yào kāi yǎnchànghuì.', 'my favourite singer|next month|will hold a concert', 'My favourite singer is giving a concert next month.', 'मेरा पसंदीदा गायक अगले महीने कॉन्सर्ट करेगा।')),
  T('books-and-reading', 'preference',
    U('这本小说|虽然很长，|但是很有意思。', 'Zhè běn xiǎoshuō|suīrán hěn cháng,|dànshì hěn yǒuyìsi.', 'this novel|although very long|is very interesting', 'Although this novel is long, it is very interesting.', 'यह उपन्यास लंबा है, फिर भी बहुत रोचक है।'),
    U('我每天睡前|会读|二十分钟。', 'Wǒ měitiān shuìqián|huì dú|èrshí fēnzhōng.', 'before sleep every day|will read|for twenty minutes', 'I read for twenty minutes before bed every day.', 'मैं रोज़ सोने से पहले बीस मिनट पढ़ता/पढ़ती हूँ।')),
  T('technology-and-phones', 'service',
    U('我的手机|连不上|无线网络。', 'Wǒ de shǒujī|lián bu shàng|wúxiàn wǎngluò.', 'my phone|cannot connect to|Wi-Fi', 'My phone cannot connect to the Wi-Fi.', 'मेरा फ़ोन वाई-फ़ाई से नहीं जुड़ रहा।'),
    U('你先|重启一下，|再检查密码。', 'Nǐ xiān|chóngqǐ yíxià,|zài jiǎnchá mìmǎ.', 'first you|restart it|then check the password', 'Restart it first, then check the password.', 'पहले इसे रीस्टार्ट करें, फिर पासवर्ड जाँचें।')),
  T('social-media', 'opinion',
    U('发照片以前，|最好先问问|别人的意见。', 'Fā zhàopiàn yǐqián,|zuìhǎo xiān wènwen|biérén de yìjiàn.', 'before posting photos|it is best to ask first|other people’s opinion', 'Before posting a photo, it is best to ask the other person.', 'फ़ोटो पोस्ट करने से पहले सामने वाले से पूछना बेहतर है।'),
    U('我只跟朋友|分享|自己的近况。', 'Wǒ zhǐ gēn péngyou|fēnxiǎng|zìjǐ de jìnkuàng.', 'only with friends I|share|my recent life', 'I share personal updates only with friends.', 'मैं निजी अपडेट केवल दोस्तों के साथ साझा करता/करती हूँ।')),
  T('work-jobs', 'identity',
    U('我在一家科技公司|做|产品设计。', 'Wǒ zài yì jiā kējì gōngsī|zuò|chǎnpǐn shèjì.', 'at a technology company I|do|product design', 'I work in product design at a technology company.', 'मैं एक टेक कंपनी में प्रोडक्ट डिज़ाइन का काम करता/करती हूँ।'),
    U('这份工作|需要|创造力和耐心。', 'Zhè fèn gōngzuò|xūyào|chuàngzàolì hé nàixīn.', 'this job|needs|creativity and patience', 'This job requires creativity and patience.', 'इस काम में रचनात्मकता और धैर्य चाहिए।')),
  T('work-office-talk', 'formal',
    U('麻烦你|把最新的文件|发给我。', 'Máfan nǐ|bǎ zuìxīn de wénjiàn|fā gěi wǒ.', 'may I trouble you|the latest file|send to me', 'Could you send me the latest file?', 'कृपया नवीनतम फ़ाइल मुझे भेज दें।'),
    U('没问题，|我下午三点以前|发给你。', 'Méi wèntí,|wǒ xiàwǔ sān diǎn yǐqián|fā gěi nǐ.', 'no problem|before 3 p.m. I|will send it to you', 'No problem. I will send it before three.', 'कोई बात नहीं, मैं तीन बजे से पहले भेज दूँगा/दूँगी।')),
  T('work-meetings', 'formal',
    U('今天的会议|主要讨论|项目进度。', 'Jīntiān de huìyì|zhǔyào tǎolùn|xiàngmù jìndù.', 'today’s meeting|mainly discusses|project progress', 'Today’s meeting will focus on project progress.', 'आज की बैठक में मुख्य रूप से प्रोजेक्ट की प्रगति पर चर्चा होगी।'),
    U('如果没有问题，|我们就|进入下一个议题。', 'Rúguǒ méiyǒu wèntí,|wǒmen jiù|jìnrù xià yí ge yìtí.', 'if there are no questions|then we|move to the next topic', 'If there are no questions, we will move to the next item.', 'यदि कोई सवाल नहीं है तो हम अगले विषय पर चलते हैं।')),
  T('school-and-education', 'formal',
    U('老师要求我们|周五以前|交作业。', 'Lǎoshī yāoqiú wǒmen|zhōuwǔ yǐqián|jiāo zuòyè.', 'the teacher requires us|before Friday|submit homework', 'The teacher asked us to submit the homework before Friday.', 'शिक्षक ने हमें शुक्रवार से पहले होमवर्क जमा करने को कहा।'),
    U('遇到不懂的地方|可以|随时提问。', 'Yùdào bù dǒng de dìfang|kěyǐ|suíshí tíwèn.', 'when you meet something unclear|you may|ask at any time', 'You can ask whenever something is unclear.', 'कुछ समझ न आए तो कभी भी पूछ सकते हैं।')),
  T('travel-planning', 'plan',
    U('我们打算|先去西安，|然后坐火车去成都。', 'Wǒmen dǎsuàn|xiān qù Xī’ān,|ránhòu zuò huǒchē qù Chéngdū.', 'we plan|first go to Xi’an|then take a train to Chengdu', 'We plan to visit Xi’an first, then take a train to Chengdu.', 'हम पहले शीआन जाने और फिर ट्रेन से चेंगदू जाने की योजना बना रहे हैं।'),
    U('出发以前|要先订好|酒店和车票。', 'Chūfā yǐqián|yào xiān dìnghǎo|jiǔdiàn hé chēpiào.', 'before departure|must book first|hotel and train tickets', 'We need to book the hotel and tickets before leaving.', 'रवाना होने से पहले होटल और टिकट बुक करने होंगे।')),
  T('hotel-checkin', 'service',
    U('您好，|我预订了|一间双人房。', 'Nín hǎo,|wǒ yùdìng le|yì jiān shuāngrénfáng.', 'hello|I reserved|a double room', 'Hello, I reserved a double room.', 'नमस्ते, मैंने एक डबल कमरा बुक किया है।'),
    U('请出示护照，|早餐|在二楼。', 'Qǐng chūshì hùzhào,|zǎocān|zài èr lóu.', 'please show your passport|breakfast|is on the second floor', 'Please show your passport. Breakfast is on the second floor.', 'कृपया पासपोर्ट दिखाएँ। नाश्ता दूसरी मंज़िल पर है।')),
  T('airport-and-flight', 'service',
    U('请问，|去上海的航班|在哪儿办理登机？', 'Qǐngwèn,|qù Shànghǎi de hángbān|zài nǎr bànlǐ dēngjī?', 'excuse me|the flight to Shanghai|where to check in', 'Where do I check in for the flight to Shanghai?', 'शंघाई की उड़ान के लिए चेक-इन कहाँ होगा?'),
    U('请到|B区十二号柜台|办理。', 'Qǐng dào|B qū shí’èr hào guìtái|bànlǐ.', 'please go to|counter 12 in zone B|to process it', 'Please check in at counter 12 in zone B.', 'कृपया बी क्षेत्र के काउंटर 12 पर चेक-इन करें।')),
  T('restaurant-deep-dive', 'service',
    U('我对花生过敏，|这道菜里|有花生吗？', 'Wǒ duì huāshēng guòmǐn,|zhè dào cài lǐ|yǒu huāshēng ma?', 'I am allergic to peanuts|inside this dish|are there peanuts', 'I am allergic to peanuts. Does this dish contain any?', 'मुझे मूँगफली से एलर्जी है; क्या इस व्यंजन में मूँगफली है?'),
    U('没有，|不过酱汁里|有芝麻。', 'Méiyǒu,|búguò jiàngzhī lǐ|yǒu zhīma.', 'no|however in the sauce|there is sesame', 'No, but the sauce contains sesame.', 'नहीं, लेकिन सॉस में तिल है।')),
  T('shopping-malls', 'service',
    U('请问，|运动鞋|在几楼？', 'Qǐngwèn,|yùndòngxié|zài jǐ lóu?', 'excuse me|sports shoes|on which floor', 'Which floor are the sports shoes on?', 'स्पोर्ट्स शूज़ किस मंज़िल पर हैं?'),
    U('在四楼，|电梯|就在前面。', 'Zài sì lóu,|diàntī|jiù zài qiánmiàn.', 'on the fourth floor|the lift|is just ahead', 'They are on the fourth floor; the lift is just ahead.', 'वे चौथी मंज़िल पर हैं; लिफ़्ट सामने है।')),
  T('doctor-visit', 'service',
    U('我从昨天开始|头疼，|还有点儿发烧。', 'Wǒ cóng zuótiān kāishǐ|tóuténg,|hái yǒudiǎnr fāshāo.', 'since yesterday I|have a headache|also have a slight fever', 'I have had a headache and a slight fever since yesterday.', 'कल से मेरे सिर में दर्द है और थोड़ा बुखार भी है।'),
    U('先量一下体温，|然后|我给你检查。', 'Xiān liáng yíxià tǐwēn,|ránhòu|wǒ gěi nǐ jiǎnchá.', 'first measure your temperature|then|I will examine you', 'Let us take your temperature first, then I will examine you.', 'पहले तापमान मापते हैं, फिर मैं जाँच करूँगा/करूँगी।')),
  T('emergencies', 'service',
    U('这里有人受伤了，|请马上|叫救护车！', 'Zhèlǐ yǒu rén shòushāng le,|qǐng mǎshàng|jiào jiùhùchē!', 'someone is injured here|please immediately|call an ambulance', 'Someone is injured; please call an ambulance now!', 'यहाँ कोई घायल है, कृपया तुरंत एम्बुलेंस बुलाएँ!'),
    U('请保持冷静，|告诉我|你们的位置。', 'Qǐng bǎochí lěngjìng,|gàosu wǒ|nǐmen de wèizhi.', 'please stay calm|tell me|your location', 'Stay calm and tell me your location.', 'शांत रहें और मुझे अपना स्थान बताएँ।')),
  T('bank-and-money', 'service',
    U('我想|开一个账户，|需要什么证件？', 'Wǒ xiǎng|kāi yí ge zhànghù,|xūyào shénme zhèngjiàn?', 'I would like|to open an account|need what documents', 'I would like to open an account. Which documents do I need?', 'मैं खाता खोलना चाहता/चाहती हूँ; कौन-से दस्तावेज़ चाहिए?'),
    U('请带护照|和|住址证明。', 'Qǐng dài hùzhào|hé|zhùzhǐ zhèngmíng.', 'please bring your passport|and|proof of address', 'Please bring your passport and proof of address.', 'कृपया पासपोर्ट और पते का प्रमाण लाएँ।')),
  T('review-conversations', 'social',
    U('我先在酒店办入住，|再去银行，|晚上跟朋友吃饭。', 'Wǒ xiān zài jiǔdiàn bàn rùzhù,|zài qù yínháng,|wǎnshang gēn péngyou chīfàn.', 'first I check in at the hotel|then go to the bank|in the evening eat with friends', 'I will check in at the hotel, visit the bank, then eat with friends.', 'मैं पहले होटल में चेक-इन करूँगा/करूँगी, फिर बैंक जाऊँगा/जाऊँगी और शाम को दोस्तों के साथ खाऊँगा/खाऊँगी।'),
    U('如果需要帮助，|随时|给我打电话。', 'Rúguǒ xūyào bāngzhù,|suíshí|gěi wǒ dǎ diànhuà.', 'if you need help|at any time|call me', 'Call me anytime if you need help.', 'मदद चाहिए तो कभी भी मुझे फ़ोन करना।')),
  T('sentence-structure', 'grammar',
    U('我|明天上午|在图书馆|学习中文。', 'Wǒ|míngtiān shàngwǔ|zài túshūguǎn|xuéxí Zhōngwén.', 'I|tomorrow morning|at the library|study Chinese', 'I will study Chinese at the library tomorrow morning.', 'मैं कल सुबह पुस्तकालय में चीनी पढ़ूँगा/पढ़ूँगी।'),
    U('中文通常按照|主语、时间、地点、动作|来安排。', 'Zhōngwén tōngcháng ànzhào|zhǔyǔ, shíjiān, dìdiǎn, dòngzuò|lái ānpái.', 'Chinese commonly follows|subject time place action|to arrange', 'Chinese commonly follows subject–time–place–action order.', 'चीनी में आम तौर पर कर्ता–समय–स्थान–क्रिया का क्रम होता है।')),
  T('question-words', 'grammar',
    U('你|为什么|想学中文？', 'Nǐ|wèishénme|xiǎng xué Zhōngwén?', 'you|why|want to learn Chinese', 'Why do you want to learn Chinese?', 'आप चीनी क्यों सीखना चाहते हैं?'),
    U('因为我想|在中国|工作。', 'Yīnwèi wǒ xiǎng|zài Zhōngguó|gōngzuò.', 'because I want|in China|to work', 'Because I want to work in China.', 'क्योंकि मैं चीन में काम करना चाहता/चाहती हूँ।')),
  T('question-particles', 'grammar',
    U('你|喝咖啡|吗？', 'Nǐ|hē kāfēi|ma?', 'you|drink coffee|question particle', 'Do you drink coffee?', 'क्या आप कॉफ़ी पीते हैं?'),
    U('我不喝咖啡，|你呢？', 'Wǒ bù hē kāfēi,|nǐ ne?', 'I do not drink coffee|and you', 'I do not drink coffee. What about you?', 'मैं कॉफ़ी नहीं पीता/पीती; आप呢?')),
  T('negation', 'grammar',
    U('我今天|不去公司，|昨天也没去。', 'Wǒ jīntiān|bú qù gōngsī,|zuótiān yě méi qù.', 'today I|am not going to the office|yesterday also did not go', 'I am not going to the office today, and I did not go yesterday either.', 'मैं आज दफ़्तर नहीं जा रहा/रही और कल भी नहीं गया/गई था।'),
    U('“不”否定习惯或将来，|“没”否定|已经发生的动作。', '“Bù” fǒudìng xíguàn huò jiānglái,|“méi” fǒudìng|yǐjīng fāshēng de dòngzuò.', 'bù negates habits or future|méi negates|completed actions', 'Use 不 for habits or future actions and 没 for completed actions.', 'आदत या भविष्य के लिए 不 और हो चुकी क्रिया के लिए 没 प्रयोग करें।')),
  T('past-tense', 'grammar',
    U('我昨天|看了|一部中国电影。', 'Wǒ zuótiān|kàn le|yí bù Zhōngguó diànyǐng.', 'yesterday I|watched|a Chinese film', 'I watched a Chinese film yesterday.', 'मैंने कल एक चीनी फ़िल्म देखी।'),
    U('看完以后，|我还写了|一篇短评。', 'Kàn wán yǐhòu,|wǒ hái xiě le|yì piān duǎnpíng.', 'after finishing it|I also wrote|a short review', 'Afterwards, I also wrote a short review.', 'देखने के बाद मैंने एक छोटी समीक्षा भी लिखी।')),
  T('future-tense', 'plan',
    U('下个月|我打算|去上海旅行。', 'Xià ge yuè|wǒ dǎsuàn|qù Shànghǎi lǚxíng.', 'next month|I plan|to travel to Shanghai', 'I plan to travel to Shanghai next month.', 'मैं अगले महीने शंघाई घूमने की योजना बना रहा/रही हूँ।'),
    U('我会提前|订机票|和酒店。', 'Wǒ huì tíqián|dìng jīpiào|hé jiǔdiàn.', 'I will in advance|book plane tickets|and a hotel', 'I will book the flight and hotel in advance.', 'मैं उड़ान और होटल पहले से बुक करूँगा/करूँगी।')),
  T('continuous-actions', 'grammar',
    U('我正在|跟客户|开视频会议。', 'Wǒ zhèngzài|gēn kèhù|kāi shìpín huìyì.', 'I am currently|with a client|having a video meeting', 'I am in a video meeting with a client.', 'मैं अभी ग्राहक के साथ वीडियो बैठक कर रहा/रही हूँ।'),
    U('请等一下，|我开完会|给你回电话。', 'Qǐng děng yíxià,|wǒ kāi wán huì|gěi nǐ huí diànhuà.', 'please wait a moment|after I finish the meeting|I will call you back', 'Please wait; I will call you back after the meeting.', 'कृपया थोड़ा रुकें, बैठक के बाद मैं वापस फ़ोन करूँगा/करूँगी।')),
  T('completed-actions', 'grammar',
    U('报告|我已经|写完了。', 'Bàogào|wǒ yǐjīng|xiě wán le.', 'the report|I already|finished writing', 'I have already finished the report.', 'मैं रिपोर्ट पहले ही पूरी कर चुका/चुकी हूँ।'),
    U('发给经理以后，|这个任务|就完成了。', 'Fā gěi jīnglǐ yǐhòu,|zhège rènwu|jiù wánchéng le.', 'after sending it to the manager|this task|will then be complete', 'The task will be complete once I send it to the manager.', 'मैनेजर को भेजने के बाद यह काम पूरा हो जाएगा।')),
  T('comparisons', 'comparison',
    U('坐地铁|比坐出租车|快得多。', 'Zuò dìtiě|bǐ zuò chūzūchē|kuài de duō.', 'taking the subway|compared with a taxi|is much faster', 'Taking the subway is much faster than taking a taxi.', 'मेट्रो लेना टैक्सी से बहुत तेज़ है।'),
    U('但是出租车|没有地铁|那么挤。', 'Dànshì chūzūchē|méiyǒu dìtiě|nàme jǐ.', 'but taxis|are not as|crowded as the subway', 'But taxis are not as crowded as the subway.', 'लेकिन टैक्सी मेट्रो जितनी भीड़ वाली नहीं होती।')),
  T('superlatives', 'comparison',
    U('这是|我们城市|最高的楼。', 'Zhè shì|wǒmen chéngshì|zuì gāo de lóu.', 'this is|in our city|the tallest building', 'This is the tallest building in our city.', 'यह हमारे शहर की सबसे ऊँची इमारत है।'),
    U('晚上从楼顶看|风景|最漂亮。', 'Wǎnshang cóng lóudǐng kàn|fēngjǐng|zuì piàoliang.', 'viewed from the roof at night|the scenery|is most beautiful', 'The view from the roof is most beautiful at night.', 'रात में छत से दृश्य सबसे सुंदर दिखता है।')),
  T('measure-words', 'quantity',
    U('请给我|两杯茶、|一碗饭和三张纸。', 'Qǐng gěi wǒ|liǎng bēi chá,|yì wǎn fàn hé sān zhāng zhǐ.', 'please give me|two cups of tea|a bowl of rice and three sheets of paper', 'Please give me two cups of tea, a bowl of rice and three sheets of paper.', 'कृपया मुझे दो कप चाय, एक कटोरा चावल और तीन कागज़ दें।'),
    U('不同的名词|要搭配|不同的量词。', 'Bùtóng de míngcí|yào dāpèi|bùtóng de liàngcí.', 'different nouns|must pair with|different measure words', 'Different nouns take different measure words.', 'अलग संज्ञाओं के साथ अलग माप-शब्द लगते हैं।')),
  T('location-words', 'location',
    U('猫|躲在沙发下面，|尾巴露在外面。', 'Māo|duǒ zài shāfā xiàmiàn,|wěiba lù zài wàimiàn.', 'the cat|hides under the sofa|its tail sticks outside', 'The cat is hiding under the sofa with its tail sticking out.', 'बिल्ली सोफ़े के नीचे छिपी है और उसकी पूँछ बाहर है।'),
    U('它的玩具|在门后面|靠墙的地方。', 'Tā de wánjù|zài mén hòumiàn|kào qiáng de dìfang.', 'its toy|is behind the door|near the wall', 'Its toy is behind the door near the wall.', 'उसका खिलौना दरवाज़े के पीछे दीवार के पास है।')),
  T('direction-words', 'location',
    U('他跑进教室，|拿起书，|又走了出来。', 'Tā pǎo jìn jiàoshì,|ná qǐ shū,|yòu zǒu le chūlái.', 'he ran into the classroom|picked up a book|walked back out', 'He ran into the classroom, picked up a book and came back out.', 'वह कक्षा में दौड़कर गया, किताब उठाई और फिर बाहर आया।'),
    U('请把箱子|搬上楼去。', 'Qǐng bǎ xiāngzi|bān shàng lóu qù.', 'please take the box|carry it upstairs away from here', 'Please carry the box upstairs.', 'कृपया डिब्बा ऊपर ले जाएँ।')),
  T('time-expressions', 'time',
    U('我学中文|已经|两年了。', 'Wǒ xué Zhōngwén|yǐjīng|liǎng nián le.', 'I have studied Chinese|already|for two years', 'I have been studying Chinese for two years.', 'मैं दो साल से चीनी सीख रहा/रही हूँ।'),
    U('从下周起，|我每天|多练半小时。', 'Cóng xià zhōu qǐ,|wǒ měitiān|duō liàn bàn xiǎoshí.', 'starting next week|every day I|will practise an extra half hour', 'Starting next week, I will practise an extra half hour every day.', 'अगले सप्ताह से मैं रोज़ आधा घंटा अधिक अभ्यास करूँगा/करूँगी।')),
  T('conditional', 'grammar',
    U('如果明天下雨，|我们就|改在家里见面。', 'Rúguǒ míngtiān xiàyǔ,|wǒmen jiù|gǎi zài jiālǐ jiànmiàn.', 'if it rains tomorrow|then we|will meet at home instead', 'If it rains tomorrow, we will meet at home instead.', 'अगर कल बारिश हुई तो हम घर पर मिलेंगे।'),
    U('只要你有时间，|什么时候来|都可以。', 'Zhǐyào nǐ yǒu shíjiān,|shénme shíhou lái|dōu kěyǐ.', 'as long as you have time|whenever you come|is fine', 'As long as you have time, you may come whenever you like.', 'जब भी समय हो, आप कभी भी आ सकते हैं।')),
  T('because-and-so', 'grammar',
    U('因为路上堵车，|所以我|迟到了十分钟。', 'Yīnwèi lùshang dǔchē,|suǒyǐ wǒ|chídào le shí fēnzhōng.', 'because traffic was congested|therefore I|was ten minutes late', 'I was ten minutes late because of traffic.', 'ट्रैफ़िक जाम था, इसलिए मैं दस मिनट देर से पहुँचा/पहुँची।'),
    U('下次我会|早点儿|出发。', 'Xià cì wǒ huì|zǎodiǎnr|chūfā.', 'next time I will|a little earlier|leave', 'I will leave earlier next time.', 'अगली बार मैं थोड़ा जल्दी निकलूँगा/निकलूँगी।')),
  T('although-and-but', 'grammar',
    U('虽然这个任务很难，|但是我们|按时完成了。', 'Suīrán zhège rènwu hěn nán,|dànshì wǒmen|ànshí wánchéng le.', 'although this task was difficult|but we|finished on time', 'Although the task was difficult, we finished it on time.', 'काम कठिन था, फिर भी हमने समय पर पूरा किया।'),
    U('过程很辛苦，|不过大家|学到了很多。', 'Guòchéng hěn xīnkǔ,|búguò dàjiā|xuédào le hěn duō.', 'the process was hard|however everyone|learned a lot', 'The process was hard, but everyone learned a lot.', 'प्रक्रिया कठिन थी, लेकिन सबने बहुत कुछ सीखा।')),
  T('when-and-while', 'grammar',
    U('我做饭的时候，|喜欢|听中文播客。', 'Wǒ zuòfàn de shíhou,|xǐhuan|tīng Zhōngwén bōkè.', 'when I cook|I like|to listen to Chinese podcasts', 'I like listening to Chinese podcasts while I cook.', 'खाना बनाते समय मुझे चीनी पॉडकास्ट सुनना पसंद है।'),
    U('听到新词时，|我会|先记下来。', 'Tīngdào xīncí shí,|wǒ huì|xiān jì xiàlái.', 'when I hear a new word|I will|write it down first', 'When I hear a new word, I write it down.', 'नया शब्द सुनते ही मैं उसे लिख लेता/लेती हूँ।')),
  T('giving-reasons', 'opinion',
    U('我选择这门课，|主要是因为|它重视口语练习。', 'Wǒ xuǎnzé zhè mén kè,|zhǔyào shì yīnwèi|tā zhòngshì kǒuyǔ liànxí.', 'I chose this course|mainly because|it values speaking practice', 'I chose this course mainly because it focuses on speaking.', 'मैंने यह कोर्स मुख्यतः इसलिए चुना क्योंकि इसमें बोलने का अभ्यास महत्वपूर्ण है।'),
    U('另一个原因是|上课时间|很合适。', 'Lìng yí ge yuányīn shì|shàngkè shíjiān|hěn héshì.', 'another reason is|the class time|is suitable', 'Another reason is that the class time suits me.', 'एक और कारण यह है कि कक्षा का समय मेरे लिए ठीक है।')),
  T('review-grammar', 'grammar',
    U('虽然我以前没学过中文，|但是只要每天练习，|就能慢慢进步。', 'Suīrán wǒ yǐqián méi xuéguo Zhōngwén,|dànshì zhǐyào měitiān liànxí,|jiù néng mànmàn jìnbù.', 'although I had not studied Chinese before|but as long as I practise daily|I can gradually improve', 'Although I had never studied Chinese, daily practice helps me improve.', 'हालाँकि मैंने पहले चीनी नहीं सीखी थी, रोज़ अभ्यास करने से धीरे-धीरे सुधार हो सकता है।'),
    U('我已经学了半年，|现在正在准备|第一次中文演讲。', 'Wǒ yǐjīng xué le bànnián,|xiànzài zhèngzài zhǔnbèi|dì yí cì Zhōngwén yǎnjiǎng.', 'I have studied for half a year|now I am preparing|my first Chinese speech', 'I have studied for six months and am preparing my first Chinese speech.', 'मैं छह महीने से सीख रहा/रही हूँ और अब अपना पहला चीनी भाषण तैयार कर रहा/रही हूँ।')),
  T('describing-people', 'description',
    U('我的同事|做事很认真，|也特别有耐心。', 'Wǒ de tóngshì|zuòshì hěn rènzhēn,|yě tèbié yǒu nàixīn.', 'my colleague|works conscientiously|is also very patient', 'My colleague is careful at work and very patient.', 'मेरे सहकर्मी काम में बहुत गंभीर और धैर्यवान हैं।'),
    U('他看起来有点儿严肃，|其实|很幽默。', 'Tā kànqǐlái yǒudiǎnr yánsù,|qíshí|hěn yōumò.', 'he looks a little serious|actually|is humorous', 'He looks serious, but he is actually very funny.', 'वह थोड़ा गंभीर दिखता है, लेकिन वास्तव में बहुत मज़ाकिया है।')),
  T('describing-places', 'description',
    U('这个小镇|靠近大海，|生活节奏很慢。', 'Zhège xiǎozhèn|kàojìn dàhǎi,|shēnghuó jiézòu hěn màn.', 'this small town|is near the sea|has a slow pace of life', 'This small town is by the sea and life moves slowly.', 'यह छोटा शहर समुद्र के पास है और जीवन की गति धीमी है।'),
    U('老街两边|都是|传统的木房子。', 'Lǎojiē liǎngbiān|dōu shì|chuántǒng de mù fángzi.', 'on both sides of the old street|all are|traditional wooden houses', 'Traditional wooden houses line both sides of the old street.', 'पुरानी सड़क के दोनों ओर पारंपरिक लकड़ी के घर हैं।')),
  T('describing-events', 'narrative',
    U('活动开始以后，|主持人先|介绍了来宾。', 'Huódòng kāishǐ yǐhòu,|zhǔchírén xiān|jièshào le láibīn.', 'after the event began|the host first|introduced the guests', 'After the event began, the host introduced the guests.', 'कार्यक्रम शुरू होने के बाद संचालक ने पहले मेहमानों का परिचय कराया।'),
    U('最后大家|一起拍照，|气氛非常热闹。', 'Zuìhòu dàjiā|yìqǐ pāizhào,|qìfēn fēicháng rènào.', 'at the end everyone|took photos together|the atmosphere was lively', 'Everyone took photos at the end, and the atmosphere was lively.', 'अंत में सबने साथ तस्वीरें लीं और माहौल बहुत उत्साहपूर्ण था।')),
  T('making-plans', 'plan',
    U('我们先确定目标，|再把任务|分成三个阶段。', 'Wǒmen xiān quèdìng mùbiāo,|zài bǎ rènwu|fēn chéng sān ge jiēduàn.', 'we first confirm the goal|then take the task|divide into three stages', 'Let us set the goal first, then divide the work into three stages.', 'पहले लक्ष्य तय करें, फिर काम को तीन चरणों में बाँटें।'),
    U('每周五|我们检查一次|完成情况。', 'Měi zhōuwǔ|wǒmen jiǎnchá yí cì|wánchéng qíngkuàng.', 'every Friday|we check once|the completion status', 'We will review progress every Friday.', 'हम हर शुक्रवार प्रगति की समीक्षा करेंगे।')),
  T('giving-advice', 'opinion',
    U('如果你想提高口语，|最好每天|录一段自己的声音。', 'Rúguǒ nǐ xiǎng tígāo kǒuyǔ,|zuìhǎo měitiān|lù yí duàn zìjǐ de shēngyīn.', 'if you want to improve speaking|it is best every day|record your own voice', 'To improve speaking, record yourself every day.', 'बोलना सुधारना है तो रोज़ अपनी आवाज़ रिकॉर्ड करना बेहतर है।'),
    U('你还可以|跟读母语者的录音，|比较语调。', 'Nǐ hái kěyǐ|gēndú mǔyǔzhě de lùyīn,|bǐjiào yǔdiào.', 'you may also|shadow a native recording|compare intonation', 'You can also shadow native audio and compare intonation.', 'आप मूल वक्ता की रिकॉर्डिंग के साथ बोलकर लहजे की तुलना भी कर सकते हैं।')),
  T('expressing-opinions', 'opinion',
    U('在我看来，|远程工作|既方便又高效。', 'Zài wǒ kànlái,|yuǎnchéng gōngzuò|jì fāngbiàn yòu gāoxiào.', 'in my view|remote work|is both convenient and efficient', 'In my view, remote work is convenient and efficient.', 'मेरे विचार में रिमोट काम सुविधाजनक और प्रभावी है।'),
    U('不过，|面对面交流|也很重要。', 'Búguò,|miànduìmiàn jiāoliú|yě hěn zhòngyào.', 'however|face-to-face communication|is also important', 'However, face-to-face communication is important too.', 'लेकिन आमने-सामने बातचीत भी महत्वपूर्ण है।')),
  T('agreeing-disagreeing', 'opinion',
    U('我理解你的观点，|但我不完全|同意这个结论。', 'Wǒ lǐjiě nǐ de guāndiǎn,|dàn wǒ bù wánquán|tóngyì zhège jiélùn.', 'I understand your viewpoint|but I do not completely|agree with this conclusion', 'I understand your point, but I do not fully agree with the conclusion.', 'मैं आपकी बात समझता/समझती हूँ, लेकिन निष्कर्ष से पूरी तरह सहमत नहीं हूँ।'),
    U('我们可以|先看看数据，|再作判断。', 'Wǒmen kěyǐ|xiān kànkan shùjù,|zài zuò pànduàn.', 'we can|first examine the data|then make a judgement', 'We can examine the data before deciding.', 'हम निर्णय से पहले डेटा देख सकते हैं।')),
  T('compliments', 'social',
    U('你的中文|进步得真快，|发音也很自然。', 'Nǐ de Zhōngwén|jìnbù de zhēn kuài,|fāyīn yě hěn zìrán.', 'your Chinese|has improved very quickly|pronunciation is natural too', 'Your Chinese has improved quickly, and your pronunciation sounds natural.', 'आपकी चीनी बहुत तेज़ी से सुधरी है और उच्चारण भी स्वाभाविक है।'),
    U('谢谢，|你的鼓励|让我更有信心。', 'Xièxie,|nǐ de gǔlì|ràng wǒ gèng yǒu xìnxīn.', 'thank you|your encouragement|makes me more confident', 'Thank you; your encouragement makes me more confident.', 'धन्यवाद, आपके प्रोत्साहन से मेरा आत्मविश्वास बढ़ा है।')),
  T('complaints', 'service',
    U('不好意思，|我点的菜|已经等了四十分钟。', 'Bù hǎoyìsi,|wǒ diǎn de cài|yǐjīng děng le sìshí fēnzhōng.', 'excuse me|the food I ordered|has taken forty minutes', 'Excuse me, I have been waiting forty minutes for my order.', 'माफ़ कीजिए, मेरे ऑर्डर को चालीस मिनट हो गए हैं।'),
    U('非常抱歉，|我马上|帮您确认。', 'Fēicháng bàoqiàn,|wǒ mǎshàng|bāng nín quèrèn.', 'very sorry|I immediately|will check for you', 'I am very sorry; I will check it immediately.', 'बहुत माफ़ी, मैं तुरंत जाँच करता/करती हूँ।')),
  T('apologies-forgiveness', 'social',
    U('对不起，|我忘了|提前通知你。', 'Duìbuqǐ,|wǒ wàng le|tíqián tōngzhī nǐ.', 'sorry|I forgot|to notify you in advance', 'I am sorry; I forgot to tell you in advance.', 'माफ़ कीजिए, मैं आपको पहले बताना भूल गया/गई।'),
    U('没关系，|下次记得|早点儿告诉我。', 'Méi guānxi,|xià cì jìde|zǎodiǎnr gàosu wǒ.', 'it is okay|next time remember|tell me earlier', 'It is okay; just tell me earlier next time.', 'कोई बात नहीं, अगली बार थोड़ा पहले बता देना।')),
  T('invitations', 'social',
    U('这个周六|你愿意来我家|一起吃饭吗？', 'Zhège zhōuliù|nǐ yuànyì lái wǒ jiā|yìqǐ chīfàn ma?', 'this Saturday|would you come to my home|eat together', 'Would you like to come to my home for dinner this Saturday?', 'क्या आप इस शनिवार मेरे घर खाने पर आना चाहेंगे?'),
    U('好啊，|我可以|带点儿甜点。', 'Hǎo a,|wǒ kěyǐ|dài diǎnr tiándiǎn.', 'sure|I can|bring some dessert', 'Sure, I can bring some dessert.', 'ज़रूर, मैं कुछ मिठाई ला सकता/सकती हूँ।')),
  T('refusing-politely', 'social',
    U('谢谢你的邀请，|可惜我那天|已经有安排了。', 'Xièxie nǐ de yāoqǐng,|kěxī wǒ nà tiān|yǐjīng yǒu ānpái le.', 'thank you for inviting me|unfortunately that day I|already have plans', 'Thank you for inviting me, but I already have plans that day.', 'निमंत्रण के लिए धन्यवाद, लेकिन उस दिन मेरी पहले से योजना है।'),
    U('没问题，|我们改天|再约。', 'Méi wèntí,|wǒmen gǎitiān|zài yuē.', 'no problem|another day we|will arrange again', 'No problem; we can meet another day.', 'कोई बात नहीं, किसी और दिन मिलेंगे।')),
  T('telephone-chinese', 'service',
    U('您好，|请问王经理|在吗？', 'Nín hǎo,|qǐngwèn Wáng jīnglǐ|zài ma?', 'hello|may I ask Manager Wang|is available', 'Hello, may I speak to Manager Wang?', 'नमस्ते, क्या मैनेजर वांग उपलब्ध हैं?'),
    U('他正在开会，|需要我|转告他吗？', 'Tā zhèngzài kāihuì,|xūyào wǒ|zhuǎngào tā ma?', 'he is in a meeting|do you need me|to pass on a message', 'He is in a meeting. Shall I give him a message?', 'वह बैठक में हैं; क्या मैं उन्हें संदेश दे दूँ?')),
  T('texting-chat', 'social',
    U('我刚看到你的消息，|不好意思|回晚了。', 'Wǒ gāng kàndào nǐ de xiāoxi,|bù hǎoyìsi|huí wǎn le.', 'I just saw your message|sorry|I replied late', 'I just saw your message; sorry for the late reply.', 'मैंने अभी आपका संदेश देखा, देर से जवाब देने के लिए माफ़ी।'),
    U('没事，|你方便的时候|再回复就好。', 'Méi shì,|nǐ fāngbiàn de shíhou|zài huífù jiù hǎo.', 'no problem|when it is convenient for you|reply then', 'No problem; reply whenever it is convenient.', 'कोई बात नहीं, सुविधा होने पर जवाब दे देना।')),
  T('formal-informal', 'formal',
    U('正式场合|可以说|“您好，请问您贵姓？”', 'Zhèngshì chǎnghé|kěyǐ shuō|“Nín hǎo, qǐngwèn nín guìxìng?”', 'in formal settings|you can say|hello may I ask your surname', 'In a formal setting, ask politely for someone’s surname.', 'औपचारिक स्थिति में किसी का उपनाम विनम्रता से पूछें।'),
    U('跟朋友见面时|说|“最近怎么样？”更自然。', 'Gēn péngyou jiànmiàn shí|shuō|“Zuìjìn zěnmeyàng?” gèng zìrán.', 'when meeting friends|say|how have you been is more natural', 'With friends, “How have you been?” sounds more natural.', 'दोस्तों से मिलते समय “हाल कैसा है?” अधिक स्वाभाविक लगता है।')),
  T('regional-differences', 'fluency',
    U('同一种食物|在不同地区|可能有不同叫法。', 'Tóng yì zhǒng shíwù|zài bùtóng dìqū|kěnéng yǒu bùtóng jiàofǎ.', 'the same food|in different regions|may have different names', 'The same food may have different names in different regions.', 'एक ही भोजन के अलग क्षेत्रों में अलग नाम हो सकते हैं।'),
    U('听不懂时|可以请对方|换一种说法。', 'Tīng bu dǒng shí|kěyǐ qǐng duìfāng|huàn yì zhǒng shuōfǎ.', 'when you do not understand|you may ask the other person|to rephrase', 'If you do not understand, ask the speaker to rephrase.', 'समझ न आए तो सामने वाले से दूसरे तरीके से कहने को कहें।')),
  T('young-people-slang', 'fluency',
    U('年轻人说“太卷了”，|常常是指|竞争压力很大。', 'Niánqīngrén shuō “tài juǎn le”,|chángcháng shì zhǐ|jìngzhēng yālì hěn dà.', 'when young people say too competitive|it often means|competitive pressure is high', 'When young people say “tài juǎn le,” they mean competition is intense.', 'युवा जब “太卷了” कहते हैं तो उसका मतलब कड़ी प्रतिस्पर्धा होता है।'),
    U('俚语变化很快，|使用以前|先确认语境。', 'Lǐyǔ biànhuà hěn kuài,|shǐyòng yǐqián|xiān quèrèn yǔjìng.', 'slang changes quickly|before using it|confirm the context', 'Slang changes quickly, so check the context before using it.', 'स्लैंग जल्दी बदलता है, इसलिए इस्तेमाल से पहले संदर्भ समझें।')),
  T('internet-language', 'fluency',
    U('聊天时“哈哈哈”|表示|觉得很好笑。', 'Liáotiān shí “hāhāhā”|biǎoshì|juéde hěn hǎoxiào.', 'in chat hahaha|shows|something is funny', 'In a chat, “哈哈哈” shows that something is funny.', 'चैट में “哈哈哈” किसी बात को मज़ेदार बताता है।'),
    U('网络缩写|适合朋友之间，|不适合正式邮件。', 'Wǎngluò suōxiě|shìhé péngyou zhījiān,|bù shìhé zhèngshì yóujiàn.', 'internet abbreviations|suit communication between friends|do not suit formal email', 'Internet abbreviations are fine with friends, not in formal email.', 'इंटरनेट संक्षेप दोस्तों के बीच ठीक हैं, औपचारिक ईमेल में नहीं।')),
  T('chengyu-basics', 'fluency',
    U('他每天坚持练习，|终于|熟能生巧。', 'Tā měitiān jiānchí liànxí,|zhōngyú|shúnéngshēngqiǎo.', 'he practised every day|finally|practice made him skilled', 'He practised every day until practice made him skilled.', 'रोज़ अभ्यास करते-करते आखिरकार उसने कौशल हासिल कर लिया।'),
    U('成语通常只有四个字，|却能表达|完整的意思。', 'Chéngyǔ tōngcháng zhǐyǒu sì ge zì,|què néng biǎodá|wánzhěng de yìsi.', 'idioms usually have only four characters|yet can express|a complete idea', 'A chengyu usually has four characters but expresses a complete idea.', 'चीनी मुहावरा अक्सर चार अक्षरों में पूरा अर्थ देता है।')),
  T('review-intermediate', 'fluency',
    U('虽然计划临时改变了，|但是大家互相帮助，|最后还是完成了任务。', 'Suīrán jìhuà línshí gǎibiàn le,|dànshì dàjiā hùxiāng bāngzhù,|zuìhòu háishi wánchéng le rènwu.', 'although the plan changed suddenly|everyone helped one another|finally still completed the task', 'Although the plan changed, everyone helped and completed the task.', 'योजना अचानक बदली, फिर भी सबने मिलकर काम पूरा किया।'),
    U('这次经历让我明白，|遇到问题时|沟通最重要。', 'Zhè cì jīnglì ràng wǒ míngbai,|yùdào wèntí shí|gōutōng zuì zhòngyào.', 'this experience made me understand|when problems occur|communication matters most', 'This experience taught me that communication matters most when problems arise.', 'इस अनुभव ने सिखाया कि समस्या आने पर संवाद सबसे महत्वपूर्ण है।')),
  T('business-meetings', 'formal',
    U('根据今天的议程，|我们先讨论预算，|再确认时间表。', 'Gēnjù jīntiān de yìchéng,|wǒmen xiān tǎolùn yùsuàn,|zài quèrèn shíjiānbiǎo.', 'according to today’s agenda|we first discuss the budget|then confirm the timeline', 'According to today’s agenda, we will discuss the budget before the timeline.', 'आज के एजेंडा के अनुसार पहले बजट, फिर समय-सारणी पर चर्चा करेंगे।'),
    U('请各部门|在会后|提交行动计划。', 'Qǐng gè bùmén|zài huìhòu|tíjiāo xíngdòng jìhuà.', 'each department please|after the meeting|submit an action plan', 'Each department should submit an action plan after the meeting.', 'हर विभाग बैठक के बाद कार्ययोजना जमा करे।')),
  T('presentations', 'formal',
    U('接下来|我将从三个方面|介绍我们的方案。', 'Jiēxiàlái|wǒ jiāng cóng sān ge fāngmiàn|jièshào wǒmen de fāng’àn.', 'next|I will from three aspects|present our proposal', 'Next, I will present our proposal from three perspectives.', 'अब मैं हमारे प्रस्ताव को तीन पहलुओं से प्रस्तुत करूँगा/करूँगी।'),
    U('如果有问题，|请在演讲结束后|提出。', 'Rúguǒ yǒu wèntí,|qǐng zài yǎnjiǎng jiéshù hòu|tíchū.', 'if there are questions|after the presentation|please raise them', 'Please hold questions until the presentation ends.', 'कृपया प्रश्न प्रस्तुति समाप्त होने के बाद पूछें।')),
  T('negotiations', 'formal',
    U('如果贵方能缩短交货期，|我们愿意|增加订单数量。', 'Rúguǒ guìfāng néng suōduǎn jiāohuòqī,|wǒmen yuànyì|zēngjiā dìngdān shùliàng.', 'if your side can shorten delivery time|we are willing|to increase order quantity', 'If you can shorten delivery, we are willing to increase the order.', 'यदि आप डिलीवरी समय घटाएँ तो हम ऑर्डर बढ़ाने को तैयार हैं।'),
    U('这个条件|原则上可以接受，|但价格需要再谈。', 'Zhège tiáojiàn|yuánzé shàng kěyǐ jiēshòu,|dàn jiàgé xūyào zài tán.', 'this condition|is acceptable in principle|but price needs more discussion', 'That condition is acceptable in principle, but we need to discuss price.', 'यह शर्त सिद्धांततः स्वीकार्य है, लेकिन कीमत पर और बात करनी होगी।')),
  T('job-interviews', 'formal',
    U('我有五年项目管理经验，|擅长|协调跨部门团队。', 'Wǒ yǒu wǔ nián xiàngmù guǎnlǐ jīngyàn,|shàncháng|xiétiáo kuà bùmén tuánduì.', 'I have five years of project management experience|am skilled at|coordinating cross-functional teams', 'I have five years of project management experience and coordinate cross-functional teams well.', 'मेरे पास पाँच साल का प्रोजेक्ट प्रबंधन अनुभव है और मैं विभिन्न विभागों का समन्वय अच्छी तरह करता/करती हूँ।'),
    U('请举一个例子，|说明你如何|解决团队冲突。', 'Qǐng jǔ yí ge lìzi,|shuōmíng nǐ rúhé|jiějué tuánduì chōngtū.', 'please give an example|explain how you|resolved team conflict', 'Give an example of how you resolved a team conflict.', 'उदाहरण देकर बताएँ कि आपने टीम का विवाद कैसे हल किया।')),
  T('marketing-sales', 'formal',
    U('这次活动的目标|是提高品牌知名度，|同时吸引新用户。', 'Zhè cì huódòng de mùbiāo|shì tígāo pǐnpái zhīmíngdù,|tóngshí xīyǐn xīn yònghù.', 'this campaign’s goal|is to raise brand awareness|while attracting new users', 'The campaign aims to build brand awareness and attract new users.', 'अभियान का लक्ष्य ब्रांड पहचान बढ़ाना और नए उपयोगकर्ता लाना है।'),
    U('我们会根据转化率|调整|广告策略。', 'Wǒmen huì gēnjù zhuǎnhuàlǜ|tiáozhěng|guǎnggào cèlüè.', 'based on conversion rate we will|adjust|the advertising strategy', 'We will adjust the advertising strategy based on conversion rate.', 'हम रूपांतरण दर के आधार पर विज्ञापन रणनीति बदलेंगे।')),
  T('financial-terms', 'formal',
    U('公司今年的收入增长了百分之十五，|但运营成本|也有所上升。', 'Gōngsī jīnnián de shōurù zēngzhǎng le bǎifēnzhī shíwǔ,|dàn yùnyíng chéngběn|yě yǒusuǒ shàngshēng.', 'company revenue grew fifteen percent this year|but operating costs|also rose somewhat', 'Revenue grew by 15 percent, but operating costs also increased.', 'कंपनी की आय 15 प्रतिशत बढ़ी, लेकिन संचालन लागत भी बढ़ी।'),
    U('因此净利润|低于|市场预期。', 'Yīncǐ jìng lìrùn|dīyú|shìchǎng yùqī.', 'therefore net profit|was lower than|market expectations', 'Therefore, net profit was below market expectations.', 'इसलिए शुद्ध लाभ बाज़ार की अपेक्षा से कम रहा।')),
  T('legal-language', 'formal',
    U('本合同|自双方签字之日起|正式生效。', 'Běn hétong|zì shuāngfāng qiānzì zhī rì qǐ|zhèngshì shēngxiào.', 'this contract|from the date both parties sign|formally takes effect', 'This contract takes effect on the date both parties sign it.', 'यह अनुबंध दोनों पक्षों के हस्ताक्षर की तारीख से प्रभावी होगा।'),
    U('任何修改|都必须|以书面形式确认。', 'Rènhé xiūgǎi|dōu bìxū|yǐ shūmiàn xíngshì quèrèn.', 'any amendment|must|be confirmed in writing', 'Any amendment must be confirmed in writing.', 'हर संशोधन की लिखित पुष्टि आवश्यक है।')),
  T('news-media', 'reading',
    U('报道指出，|该政策将于明年|正式实施。', 'Bàodào zhǐchū,|gāi zhèngcè jiāng yú míngnián|zhèngshì shíshī.', 'the report points out|the policy next year|will be implemented', 'The report says the policy will be implemented next year.', 'रिपोर्ट के अनुसार नीति अगले वर्ष लागू होगी।'),
    U('专家认为|它可能对就业市场|产生长期影响。', 'Zhuānjiā rènwéi|tā kěnéng duì jiùyè shìchǎng|chǎnshēng chángqī yǐngxiǎng.', 'experts believe|it may on the job market|have a long-term effect', 'Experts believe it may have a long-term effect on employment.', 'विशेषज्ञों का मानना है कि रोजगार बाज़ार पर इसका दीर्घकालीन प्रभाव पड़ सकता है।')),
  T('politics-society', 'opinion',
    U('公共政策的制定|需要兼顾|效率与公平。', 'Gōnggòng zhèngcè de zhìdìng|xūyào jiāngù|xiàolǜ yǔ gōngpíng.', 'making public policy|needs to balance|efficiency and fairness', 'Public policy must balance efficiency with fairness.', 'सार्वजनिक नीति में दक्षता और न्याय दोनों का संतुलन होना चाहिए।'),
    U('不同群体的声音|都应该|被认真听取。', 'Bùtóng qúntǐ de shēngyīn|dōu yīnggāi|bèi rènzhēn tīngqǔ.', 'voices of different groups|should all|be heard carefully', 'The voices of different groups should all be heard.', 'विभिन्न समूहों की आवाज़ गंभीरता से सुनी जानी चाहिए।')),
  T('history-culture', 'narrative',
    U('这座古城|保存了|许多明清时期的建筑。', 'Zhè zuò gǔchéng|bǎocún le|xǔduō Míng-Qīng shíqī de jiànzhù.', 'this ancient city|has preserved|many Ming and Qing buildings', 'This ancient city preserves many buildings from the Ming and Qing eras.', 'इस प्राचीन शहर में मिंग और छिंग काल की कई इमारतें सुरक्षित हैं।'),
    U('了解历史背景|能帮助我们|理解当地文化。', 'Liǎojiě lìshǐ bèijǐng|néng bāngzhù wǒmen|lǐjiě dāngdì wénhuà.', 'understanding historical context|can help us|understand local culture', 'Historical context helps us understand local culture.', 'ऐतिहासिक पृष्ठभूमि स्थानीय संस्कृति समझने में मदद करती है।')),
  T('philosophy-religion', 'opinion',
    U('这个思想强调|个人选择|与社会责任之间的关系。', 'Zhège sīxiǎng qiángdiào|gèrén xuǎnzé|yǔ shèhuì zérèn zhījiān de guānxi.', 'this idea emphasizes|personal choice|and its relationship with social responsibility', 'This idea emphasizes the relationship between personal choice and social responsibility.', 'यह विचार व्यक्तिगत चुनाव और सामाजिक जिम्मेदारी के संबंध पर ज़ोर देता है।'),
    U('讨论信仰时|应该尊重|不同的价值观。', 'Tǎolùn xìnyǎng shí|yīnggāi zūnzhòng|bùtóng de jiàzhíguān.', 'when discussing belief|one should respect|different values', 'Discussions of belief should respect different values.', 'आस्था पर चर्चा करते समय अलग मूल्यों का सम्मान करना चाहिए।')),
  T('arts-literature', 'opinion',
    U('这部小说|通过普通人的生活|反映了时代变化。', 'Zhè bù xiǎoshuō|tōngguò pǔtōng rén de shēnghuó|fǎnyìng le shídài biànhuà.', 'this novel|through ordinary people’s lives|reflects social change', 'The novel reflects social change through ordinary people’s lives.', 'यह उपन्यास आम लोगों के जीवन से युग के बदलाव दिखाता है।'),
    U('作者的语言|看似简单，|其实很有层次。', 'Zuòzhě de yǔyán|kànsì jiǎndān,|qíshí hěn yǒu céngcì.', 'the author’s language|seems simple|actually has many layers', 'The author’s language seems simple but is richly layered.', 'लेखक की भाषा सरल दिखती है, लेकिन उसमें कई स्तर हैं।')),
  T('science-technology', 'formal',
    U('人工智能正在|改变|人们获取信息的方式。', 'Réngōng zhìnéng zhèngzài|gǎibiàn|rénmen huòqǔ xìnxī de fāngshì.', 'artificial intelligence is|changing|how people access information', 'Artificial intelligence is changing how people access information.', 'कृत्रिम बुद्धिमत्ता लोगों के जानकारी पाने के तरीके बदल रही है।'),
    U('技术发展越快，|数据安全|就越重要。', 'Jìshù fāzhǎn yuè kuài,|shùjù ānquán|jiù yuè zhòngyào.', 'the faster technology develops|data security|becomes more important', 'The faster technology advances, the more important data security becomes.', 'तकनीक जितनी तेज़ बढ़ती है, डेटा सुरक्षा उतनी महत्वपूर्ण होती है।')),
  T('environment', 'opinion',
    U('减少一次性塑料|需要消费者、企业和政府|共同参与。', 'Jiǎnshǎo yícìxìng sùliào|xūyào xiāofèizhě, qǐyè hé zhèngfǔ|gòngtóng cānyù.', 'reducing single-use plastic|needs consumers businesses and government|to participate together', 'Reducing single-use plastic requires consumers, businesses and government.', 'एक बार इस्तेमाल होने वाले प्लास्टिक को घटाने में जनता, कंपनियों और सरकार सभी की भागीदारी चाहिए।'),
    U('个人的小改变|长期坚持下去|也会产生影响。', 'Gèrén de xiǎo gǎibiàn|chángqī jiānchí xiàqù|yě huì chǎnshēng yǐngxiǎng.', 'small personal changes|if continued long term|also make an impact', 'Small personal changes can have an impact when sustained.', 'व्यक्तिगत छोटे बदलाव भी लगातार किए जाएँ तो असर डालते हैं।')),
  T('education-systems', 'formal',
    U('教育体系|不仅要传授知识，|还要培养独立思考。', 'Jiàoyù tǐxì|bùjǐn yào chuánshòu zhīshi,|hái yào péiyǎng dúlì sīkǎo.', 'an education system|must not only teach knowledge|but also develop independent thought', 'Education should teach knowledge and develop independent thinking.', 'शिक्षा को ज्ञान के साथ स्वतंत्र सोच भी विकसित करनी चाहिए।'),
    U('评价学生时|不能只看|一次考试的分数。', 'Píngjià xuésheng shí|bù néng zhǐ kàn|yí cì kǎoshì de fēnshù.', 'when evaluating students|one cannot only look at|one exam score', 'Students should not be judged by a single exam score.', 'विद्यार्थियों का मूल्यांकन केवल एक परीक्षा के अंक से नहीं होना चाहिए।')),
  T('healthcare-system', 'formal',
    U('完善的基层医疗|能够减轻|大医院的压力。', 'Wánshàn de jīcéng yīliáo|nénggòu jiǎnqīng|dà yīyuàn de yālì.', 'strong primary healthcare|can reduce|pressure on major hospitals', 'Strong primary healthcare can reduce pressure on major hospitals.', 'मज़बूत प्राथमिक स्वास्थ्य सेवा बड़े अस्पतालों का दबाव कम कर सकती है।'),
    U('预防疾病|和治疗疾病|同样重要。', 'Yùfáng jíbìng|hé zhìliáo jíbìng|tóngyàng zhòngyào.', 'preventing illness|and treating illness|are equally important', 'Prevention is as important as treatment.', 'बीमारी की रोकथाम उपचार जितनी ही महत्वपूर्ण है।')),
  T('real-estate', 'service',
    U('这套公寓|交通方便，|但管理费比较高。', 'Zhè tào gōngyù|jiāotōng fāngbiàn,|dàn guǎnlǐfèi bǐjiào gāo.', 'this apartment|has convenient transport|but high maintenance fees', 'The apartment is well connected, but its maintenance fee is high.', 'इस अपार्टमेंट से आवागमन आसान है, लेकिन रखरखाव शुल्क अधिक है।'),
    U('签租约以前|要仔细确认|押金和维修责任。', 'Qiān zūyuē yǐqián|yào zǐxì quèrèn|yājīn hé wéixiū zérèn.', 'before signing a lease|carefully confirm|deposit and repair responsibility', 'Check the deposit and repair responsibilities before signing a lease.', 'किराया अनुबंध से पहले जमा राशि और मरम्मत की जिम्मेदारी जाँचें।')),
  T('entertainment-industry', 'formal',
    U('流媒体平台的兴起|改变了|观众的观看习惯。', 'Liúméitǐ píngtái de xīngqǐ|gǎibiàn le|guānzhòng de guānkàn xíguàn.', 'the rise of streaming platforms|changed|viewing habits', 'The rise of streaming platforms has changed viewing habits.', 'स्ट्रीमिंग प्लेटफ़ॉर्म ने दर्शकों की देखने की आदतें बदल दी हैं।'),
    U('一部作品的成功|往往取决于|内容与发行策略。', 'Yí bù zuòpǐn de chénggōng|wǎngwǎng qǔjuéyú|nèiróng yǔ fāxíng cèlüè.', 'a work’s success|often depends on|content and distribution strategy', 'A production’s success often depends on content and distribution.', 'किसी रचना की सफलता अक्सर सामग्री और वितरण रणनीति पर निर्भर करती है।')),
  T('tourism-deep-dive', 'opinion',
    U('发展旅游业|应该在经济收益和文化保护之间|找到平衡。', 'Fāzhǎn lǚyóuyè|yīnggāi zài jīngjì shōuyì hé wénhuà bǎohù zhījiān|zhǎodào pínghéng.', 'developing tourism|between economic gains and cultural protection|should find balance', 'Tourism development should balance economic benefit and cultural protection.', 'पर्यटन विकास में आर्थिक लाभ और संस्कृति संरक्षण का संतुलन होना चाहिए।'),
    U('负责任的游客|会尊重|当地社区的生活方式。', 'Fù zérèn de yóukè|huì zūnzhòng|dāngdì shèqū de shēnghuó fāngshì.', 'responsible tourists|will respect|local ways of life', 'Responsible tourists respect the local community’s way of life.', 'जिम्मेदार पर्यटक स्थानीय समुदाय के जीवन का सम्मान करते हैं।')),
  T('review-advanced', 'formal',
    U('面对复杂问题，|我们既要分析数据，|也要考虑政策的长期影响。', 'Miànduì fùzá wèntí,|wǒmen jì yào fēnxī shùjù,|yě yào kǎolǜ zhèngcè de chángqī yǐngxiǎng.', 'when facing complex problems|we must analyse data|and consider long-term policy effects', 'Complex problems require data analysis and long-term policy thinking.', 'जटिल समस्याओं में डेटा और नीति के दीर्घकालीन प्रभाव दोनों देखने चाहिए।'),
    U('只有听取不同意见，|才有可能|作出更全面的判断。', 'Zhǐyǒu tīngqǔ bùtóng yìjiàn,|cái yǒu kěnéng|zuòchū gèng quánmiàn de pànduàn.', 'only by hearing different views|is it possible|to make a fuller judgement', 'Only by hearing different views can we make a well-rounded judgement.', 'अलग राय सुनकर ही व्यापक निर्णय लिया जा सकता है।')),
  T('character-basics', 'reading',
    U('“休”字|由“人”和“木”|组成。', '“Xiū” zì|yóu “rén” hé “mù”|zǔchéng.', 'the character rest|from person and tree|is formed', 'The character 休 is formed from “person” and “tree.”', '“休” अक्षर “मनुष्य” और “पेड़” से बनता है।'),
    U('理解部件|可以帮助你|记住汉字。', 'Lǐjiě bùjiàn|kěyǐ bāngzhù nǐ|jìzhù Hànzì.', 'understanding components|can help you|remember characters', 'Understanding components helps you remember characters.', 'अक्षर के भाग समझने से चीनी अक्षर याद रहते हैं।')),
  T('character-formation', 'reading',
    U('形声字|通常一部分表示意义，|另一部分提示读音。', 'Xíngshēngzì|tōngcháng yí bùfen biǎoshì yìyì,|lìng yí bùfen tíshì dúyīn.', 'phonetic-semantic characters|one part usually shows meaning|another suggests pronunciation', 'In phonetic-semantic characters, one part suggests meaning and another sound.', 'ध्वनि-अर्थ अक्षरों में एक भाग अर्थ और दूसरा उच्चारण बताता है।'),
    U('比如“河”的三点水|跟|水有关。', 'Bǐrú “hé” de sāndiǎnshuǐ|gēn|shuǐ yǒuguān.', 'for example the water radical in river|with|water is related', 'For example, the water radical in 河 signals a link to water.', 'उदाहरण में “河” का जल-चिह्न पानी से संबंध बताता है।')),
  T('reading-signs', 'reading',
    U('看到“禁止吸烟”|就表示|这里不能抽烟。', 'Kàndào “jìnzhǐ xīyān”|jiù biǎoshì|zhèlǐ bù néng chōuyān.', 'when you see no smoking|it means|you cannot smoke here', '“禁止吸烟” means that smoking is not allowed.', '“禁止吸烟” का मतलब है यहाँ धूम्रपान मना है।'),
    U('“小心地滑”|提醒你|地面可能很滑。', '“Xiǎoxīn dì huá”|tíxǐng nǐ|dìmiàn kěnéng hěn huá.', 'caution slippery floor|reminds you|the ground may be slippery', '“小心地滑” warns that the floor may be slippery.', '“小心地滑” फिसलन से सावधान रहने की चेतावनी है।')),
  T('reading-menus', 'reading',
    U('菜单上的“清蒸”|表示|用蒸的方法做。', 'Càidān shàng de “qīngzhēng”|biǎoshì|yòng zhēng de fāngfǎ zuò.', 'steamed on a menu|means|cooked by steaming', 'On a menu, 清蒸 means the food is steamed.', 'मेन्यू में “清蒸” का मतलब भाप में पकाया हुआ है।'),
    U('“招牌菜”|通常是|餐厅最有特色的菜。', '“Zhāopáicài”|tōngcháng shì|cāntīng zuì yǒu tèsè de cài.', 'signature dish|usually is|the restaurant’s special dish', 'A 招牌菜 is usually the restaurant’s signature dish.', '“招牌菜” रेस्तरां का विशेष व्यंजन होता है।')),
  T('reading-messages', 'reading',
    U('通知上写着|会议提前到|上午九点。', 'Tōngzhī shàng xiězhe|huìyì tíqián dào|shàngwǔ jiǔ diǎn.', 'the notice says|the meeting was moved earlier to|9 a.m.', 'The notice says the meeting has been moved to 9 a.m.', 'सूचना में लिखा है कि बैठक सुबह नौ बजे कर दी गई है।'),
    U('最后一句|要求大家|准时参加。', 'Zuìhòu yí jù|yāoqiú dàjiā|zhǔnshí cānjiā.', 'the final sentence|asks everyone|to attend on time', 'The last sentence asks everyone to attend on time.', 'अंतिम वाक्य सबको समय पर आने को कहता है।')),
  T('short-stories-1', 'narrative',
    U('小林第一次去北京，|下车以后|却找不到酒店。', 'Xiǎo Lín dì yí cì qù Běijīng,|xiàchē yǐhòu|què zhǎo bu dào jiǔdiàn.', 'Xiao Lin went to Beijing for the first time|after getting off|could not find the hotel', 'On his first trip to Beijing, Xiao Lin could not find his hotel.', 'पहली बार बीजिंग पहुँचे श्याओ लिन को होटल नहीं मिला।'),
    U('一位老人|看了地址，|亲自带他走到门口。', 'Yí wèi lǎorén|kàn le dìzhǐ,|qīnzì dài tā zǒu dào ménkǒu.', 'an elderly person|looked at the address|personally led him to the entrance', 'An elderly man read the address and walked him to the entrance.', 'एक बुज़ुर्ग ने पता देखकर उन्हें होटल के दरवाज़े तक पहुँचाया।')),
  T('short-stories-2', 'narrative',
    U('雨停以后，|女孩发现窗外|出现了一道彩虹。', 'Yǔ tíng yǐhòu,|nǚhái fāxiàn chuāngwài|chūxiàn le yí dào cǎihóng.', 'after the rain stopped|the girl noticed outside|a rainbow appeared', 'After the rain stopped, the girl saw a rainbow outside.', 'बारिश रुकने के बाद लड़की ने बाहर इंद्रधनुष देखा।'),
    U('她拿起相机，|却决定先用眼睛|记住这一刻。', 'Tā náqǐ xiàngjī,|què juédìng xiān yòng yǎnjing|jìzhù zhè yí kè.', 'she picked up the camera|but decided first with her eyes|to remember the moment', 'She picked up her camera, then chose to experience the moment first.', 'उसने कैमरा उठाया, फिर पहले उस पल को आँखों से जीने का फैसला किया।')),
  T('famous-fables', 'narrative',
    U('农夫守在树旁|等待兔子，|却荒废了田地。', 'Nóngfū shǒu zài shù páng|děngdài tùzi,|què huāngfèi le tiándì.', 'the farmer waited by the tree|for a rabbit|but neglected his field', 'The farmer waited by the tree for another rabbit and neglected his field.', 'किसान खरगोश की प्रतीक्षा में पेड़ के पास बैठा रहा और खेत बिगड़ गया।'),
    U('“守株待兔”告诉我们|不能只靠运气|获得成功。', '“Shǒuzhūdàitù” gàosu wǒmen|bù néng zhǐ kào yùnqi|huòdé chénggōng.', 'waiting for a rabbit teaches us|we cannot rely only on luck|to succeed', 'The fable teaches us not to rely on luck for success.', 'यह कथा सिखाती है कि सफलता के लिए केवल भाग्य पर निर्भर नहीं रहना चाहिए।')),
  T('modern-stories', 'narrative',
    U('搬到陌生城市以后，|她通过社区活动|认识了新朋友。', 'Bān dào mòshēng chéngshì yǐhòu,|tā tōngguò shèqū huódòng|rènshi le xīn péngyou.', 'after moving to an unfamiliar city|through community events she|met new friends', 'After moving to a new city, she made friends through community events.', 'नए शहर में जाकर उसने सामुदायिक कार्यक्रमों से दोस्त बनाए।'),
    U('原来归属感|不是等来的，|而是慢慢建立的。', 'Yuánlái guīshǔgǎn|bú shì děng lái de,|ér shì mànmàn jiànlì de.', 'a sense of belonging|is not something that comes by waiting|but is built gradually', 'She learned that belonging is built gradually, not simply awaited.', 'उसे समझ आया कि अपनापन प्रतीक्षा से नहीं, धीरे-धीरे बनता है।')),
  T('poetry-basics', 'reading',
    U('诗歌常用简短的语言|创造|丰富的画面。', 'Shīgē cháng yòng jiǎnduǎn de yǔyán|chuàngzào|fēngfù de huàmiàn.', 'poetry often uses concise language|to create|rich imagery', 'Poetry uses concise language to create rich imagery.', 'कविता कम शब्दों में समृद्ध दृश्य बनाती है।'),
    U('读诗时|要注意|节奏、意象和留白。', 'Dú shī shí|yào zhùyì|jiézòu, yìxiàng hé liúbái.', 'when reading poetry|pay attention to|rhythm imagery and what is unsaid', 'When reading poetry, notice rhythm, imagery and what is left unsaid.', 'कविता पढ़ते समय लय, बिंब और अनकही जगह पर ध्यान दें।')),
  T('tang-poetry', 'reading',
    U('“举头望明月”|描写诗人|抬头看月亮。', '“Jǔ tóu wàng míngyuè”|miáoxiě shīrén|táitóu kàn yuèliang.', 'raise head and gaze at moon|describes the poet|looking up at the moon', '“举头望明月” depicts the poet looking up at the moon.', '“举头望明月” कवि के चाँद की ओर देखने का दृश्य है।'),
    U('下一句借月光|表达了|对故乡的思念。', 'Xià yí jù jiè yuèguāng|biǎodá le|duì gùxiāng de sīniàn.', 'the next line uses moonlight|to express|longing for home', 'The next line uses moonlight to express longing for home.', 'अगली पंक्ति चाँदनी से घर की याद व्यक्त करती है।')),
  T('news-articles', 'reading',
    U('阅读新闻时|先区分|事实、引用和评论。', 'Yuèdú xīnwén shí|xiān qūfēn|shìshí, yǐnyòng hé pínglùn.', 'when reading news|first distinguish|fact quotation and commentary', 'When reading news, distinguish facts, quotations and commentary.', 'समाचार पढ़ते समय तथ्य, उद्धरण और टिप्पणी अलग पहचानें।'),
    U('标题吸引注意，|但完整语境|通常在正文里。', 'Biāotí xīyǐn zhùyì,|dàn wánzhěng yǔjìng|tōngcháng zài zhèngwén lǐ.', 'headlines attract attention|but full context|is usually in the article', 'Headlines attract attention, but the full context is in the article.', 'शीर्षक ध्यान खींचता है, पूरा संदर्भ लेख में मिलता है।')),
  T('blogs-social', 'reading',
    U('这篇博客|用轻松的语气|记录了作者的旅行。', 'Zhè piān bókè|yòng qīngsōng de yǔqì|jìlù le zuòzhě de lǚxíng.', 'this blog post|in a relaxed tone|records the author’s trip', 'This blog post describes the author’s trip in a relaxed tone.', 'यह ब्लॉग लेखक की यात्रा को हल्के अंदाज़ में बताता है।'),
    U('评论区里的观点|很有趣，|但不一定可靠。', 'Pínglùnqū lǐ de guāndiǎn|hěn yǒuqù,|dàn bù yídìng kěkào.', 'opinions in the comments|are interesting|but not necessarily reliable', 'Comments may be interesting, but they are not always reliable.', 'टिप्पणियों की राय रोचक हो सकती है, पर हमेशा विश्वसनीय नहीं।')),
  T('business-documents', 'formal',
    U('这份报告的摘要|概括了|主要发现和建议。', 'Zhè fèn bàogào de zhāiyào|gàikuò le|zhǔyào fāxiàn hé jiànyì.', 'this report’s executive summary|summarizes|main findings and recommendations', 'The executive summary covers the report’s main findings and recommendations.', 'रिपोर्ट का सार मुख्य निष्कर्ष और सुझाव बताता है।'),
    U('附录中|列出了|完整的数据来源。', 'Fùlù zhōng|lièchū le|wánzhěng de shùjù láiyuán.', 'in the appendix|are listed|the complete data sources', 'The appendix lists the complete data sources.', 'परिशिष्ट में डेटा के सभी स्रोत दिए गए हैं।')),
  T('review-reading', 'reading',
    U('面对不同文本，|先判断目的，|再选择阅读方法。', 'Miànduì bùtóng wénběn,|xiān pànduàn mùdì,|zài xuǎnzé yuèdú fāngfǎ.', 'when facing different texts|first identify the purpose|then choose a reading method', 'Identify a text’s purpose before choosing how to read it.', 'अलग पाठ पढ़ते समय पहले उद्देश्य पहचानें, फिर पढ़ने की विधि चुनें।'),
    U('标志要快速识别，|故事要跟踪情节，|报告要寻找证据。', 'Biāozhì yào kuàisù shíbié,|gùshi yào gēnzōng qíngjié,|bàogào yào xúnzhǎo zhèngjù.', 'signs require quick recognition|stories require tracking plot|reports require finding evidence', 'Scan signs, follow plots in stories and seek evidence in reports.', 'चिह्न जल्दी पहचानें, कहानी का क्रम पकड़ें और रिपोर्ट में प्रमाण खोजें।')),
  T('natural-flow', 'fluency',
    U('这个问题嘛，|我得先想一想，|再回答你。', 'Zhège wèntí ma,|wǒ děi xiān xiǎng yì xiǎng,|zài huídá nǐ.', 'as for this question|I need to think first|then answer you', 'As for that question, let me think before I answer.', 'इस सवाल पर मुझे पहले थोड़ा सोचने दें, फिर जवाब दूँगा/दूँगी।'),
    U('停顿和连接词|能让表达|更自然。', 'Tíngdùn hé liánjiēcí|néng ràng biǎodá|gèng zìrán.', 'pauses and connectors|can make expression|more natural', 'Pauses and connectors make speech sound more natural.', 'ठहराव और जोड़ने वाले शब्द बोलने को अधिक स्वाभाविक बनाते हैं।')),
  T('storytelling', 'narrative',
    U('事情要从三年前说起，|当时我刚搬到|一座陌生的城市。', 'Shìqing yào cóng sān nián qián shuōqǐ,|dāngshí wǒ gāng bān dào|yí zuò mòshēng de chéngshì.', 'the story begins three years ago|at that time I had just moved to|an unfamiliar city', 'The story begins three years ago, when I had just moved to a new city.', 'कहानी तीन साल पहले शुरू होती है, जब मैं एक अनजान शहर में आया/आई था।'),
    U('没想到一次偶然的相遇|彻底改变了|我的生活。', 'Méi xiǎngdào yí cì ǒurán de xiāngyù|chèdǐ gǎibiàn le|wǒ de shēnghuó.', 'unexpectedly a chance meeting|completely changed|my life', 'Unexpectedly, a chance meeting completely changed my life.', 'एक अचानक मुलाकात ने मेरा जीवन पूरी तरह बदल दिया।')),
  T('debating', 'opinion',
    U('你的论点有一定道理，|但这个例子|不足以证明普遍结论。', 'Nǐ de lùndiǎn yǒu yídìng dàolǐ,|dàn zhège lìzi|bùzúyǐ zhèngmíng pǔbiàn jiélùn.', 'your argument has some merit|but this example|cannot prove a general conclusion', 'Your argument has merit, but one example cannot prove a general conclusion.', 'आपकी दलील ठीक है, पर एक उदाहरण से सामान्य निष्कर्ष सिद्ध नहीं होता।'),
    U('我们需要|更广泛的数据|来支持这个观点。', 'Wǒmen xūyào|gèng guǎngfàn de shùjù|lái zhīchí zhège guāndiǎn.', 'we need|broader data|to support this view', 'We need broader data to support that view.', 'इस विचार के समर्थन के लिए व्यापक डेटा चाहिए।')),
  T('humor-jokes', 'fluency',
    U('这个笑话的妙处|在于|同一个词有两层意思。', 'Zhège xiàohua de miàochù|zàiyú|tóng yí ge cí yǒu liǎng céng yìsi.', 'the cleverness of this joke|lies in|one word having two meanings', 'The joke works because one word has two meanings.', 'इस मज़ाक की खासियत एक शब्द के दो अर्थ हैं।'),
    U('翻译以后不好笑，|是因为|双关语消失了。', 'Fānyì yǐhòu bù hǎoxiào,|shì yīnwèi|shuāngguānyǔ xiāoshī le.', 'after translation it is not funny|because|the pun disappears', 'It stops being funny in translation because the pun disappears.', 'अनुवाद में शब्द-खेल खोने से मज़ाक का असर चला जाता है।')),
  T('idioms-mastery', 'fluency',
    U('这个方案看起来大胆，|其实是经过深思熟虑的，|并非异想天开。', 'Zhège fāng’àn kànqǐlái dàdǎn,|qíshí shì jīngguò shēnsīshúlǜ de,|bìngfēi yìxiǎngtiānkāi.', 'this plan looks bold|actually it was carefully considered|not a wild fantasy', 'The plan looks bold, but it is carefully considered, not wishful thinking.', 'योजना साहसी दिखती है, पर अच्छी तरह सोची गई है, केवल कल्पना नहीं।'),
    U('成语用得准确|可以让表达|更简洁有力。', 'Chéngyǔ yòng de zhǔnquè|kěyǐ ràng biǎodá|gèng jiǎnjié yǒulì.', 'using idioms accurately|can make expression|more concise and forceful', 'Accurate idioms make expression concise and powerful.', 'सही मुहावरे अभिव्यक्ति को संक्षिप्त और प्रभावी बनाते हैं।')),
  T('proverbs-sayings', 'fluency',
    U('俗话说“慢工出细活”，|有些事情|急不得。', 'Súhuà shuō “màngōng chū xìhuó”,|yǒuxiē shìqing|jí bu dé.', 'as the saying goes slow work yields fine work|some things|cannot be rushed', 'As the saying goes, careful work takes time; some things cannot be rushed.', 'कहावत है कि अच्छा काम समय लेता है; कुछ चीज़ों में जल्दी नहीं करनी चाहिए।'),
    U('引用谚语时|要确保|它真的适合当前语境。', 'Yǐnyòng yànyǔ shí|yào quèbǎo|tā zhēn de shìhé dāngqián yǔjìng.', 'when quoting a proverb|make sure|it fits the current context', 'Make sure a proverb truly fits the context before quoting it.', 'कहावत बोलने से पहले देखें कि वह संदर्भ में सही बैठती है।')),
  T('emotional-expression', 'fluency',
    U('听到你平安回来，|我心里的石头|总算落地了。', 'Tīngdào nǐ píng’ān huílái,|wǒ xīnli de shítou|zǒngsuàn luòdì le.', 'hearing you returned safely|the stone in my heart|finally fell to the ground', 'Hearing you returned safely was an enormous relief.', 'आपके सुरक्षित लौटने की खबर से मुझे बड़ी राहत मिली।'),
    U('有些感受|直译很生硬，|需要用自然的中文表达。', 'Yǒuxiē gǎnshòu|zhíyì hěn shēngyìng,|xūyào yòng zìrán de Zhōngwén biǎodá.', 'some feelings|sound stiff if translated literally|need natural Chinese expression', 'Some feelings need natural Chinese rather than literal translation.', 'कुछ भावों को शाब्दिक नहीं, स्वाभाविक चीनी में कहना चाहिए।')),
  T('persuasion', 'formal',
    U('与其只关注短期成本，|不如考虑|这项投资带来的长期价值。', 'Yǔqí zhǐ guānzhù duǎnqī chéngběn,|bùrú kǎolǜ|zhè xiàng tóuzī dàilái de chángqī jiàzhí.', 'rather than focus only on short-term cost|it is better to consider|the long-term value of this investment', 'Rather than focus on short-term cost, consider the investment’s long-term value.', 'केवल अल्पकालीन लागत देखने के बजाय निवेश का दीर्घकालीन मूल्य देखें।'),
    U('如果现在采取行动，|我们就能|降低未来的风险。', 'Rúguǒ xiànzài cǎiqǔ xíngdòng,|wǒmen jiù néng|jiàngdī wèilái de fēngxiǎn.', 'if we act now|then we can|reduce future risk', 'Acting now will reduce future risk.', 'अभी कदम उठाने से भविष्य का जोखिम कम होगा।')),
  T('cultural-nuances', 'fluency',
    U('对方说“有空再联系”|有时只是礼貌表达，|不一定是具体约定。', 'Duìfāng shuō “yǒu kòng zài liánxì”|yǒushí zhǐshì lǐmào biǎodá,|bù yídìng shì jùtǐ yuēdìng.', 'when someone says let us talk when free|sometimes it is only polite|not necessarily a firm plan', '“Let us catch up sometime” may be polite rather than a firm plan.', '“फिर कभी संपर्क करेंगे” कभी केवल शिष्टाचार होता है, पक्का वादा नहीं।'),
    U('理解言外之意|需要结合|关系、语气和场合。', 'Lǐjiě yánwàizhīyì|xūyào jiéhé|guānxi, yǔqì hé chǎnghé.', 'understanding implied meaning|requires combining|relationship tone and setting', 'Understanding implied meaning requires context, tone and relationship.', 'छिपा अर्थ समझने के लिए संबंध, लहजा और स्थिति साथ देखनी होती है।')),
  T('professional-fluency', 'formal',
    U('就目前掌握的信息来看，|项目总体可行，|但仍存在执行风险。', 'Jiù mùqián zhǎngwò de xìnxī lái kàn,|xiàngmù zǒngtǐ kěxíng,|dàn réng cúnzài zhíxíng fēngxiǎn.', 'based on current information|the project is broadly feasible|but execution risks remain', 'Based on current information, the project is viable but execution risks remain.', 'वर्तमान जानकारी के आधार पर परियोजना संभव है, लेकिन क्रियान्वयन जोखिम बाकी हैं।'),
    U('建议在正式启动前|先完成|小规模测试。', 'Jiànyì zài zhèngshì qǐdòng qián|xiān wánchéng|xiǎo guīmó cèshì.', 'it is recommended before formal launch|first complete|a small-scale test', 'I recommend a small pilot before the formal launch.', 'औपचारिक शुरुआत से पहले छोटा परीक्षण करना उचित है।')),
  T('media-fluency', 'reading',
    U('这篇评论|表面上讨论消费趋势，|实际上在质疑社会价值观。', 'Zhè piān pínglùn|biǎomiàn shàng tǎolùn xiāofèi qūshì,|shíjì shàng zài zhìyí shèhuì jiàzhíguān.', 'this commentary|seemingly discusses consumer trends|actually questions social values', 'The commentary appears to discuss consumer trends but really questions social values.', 'यह टिप्पणी ऊपर से उपभोग प्रवृत्ति पर है, असल में सामाजिक मूल्यों पर सवाल करती है।'),
    U('作者通过反问|引导读者|重新审视自己的立场。', 'Zuòzhě tōngguò fǎnwèn|yǐndǎo dúzhě|chóngxīn shěnshì zìjǐ de lìchǎng.', 'through rhetorical questions the author|guides readers|to reconsider their stance', 'Rhetorical questions lead readers to reconsider their position.', 'लेखक प्रश्नों से पाठक को अपनी स्थिति फिर जाँचने को प्रेरित करता है।')),
  T('dialect-awareness', 'fluency',
    U('普通话能让各地的人沟通，|但方言也承载着|地方文化和身份。', 'Pǔtōnghuà néng ràng gèdì de rén gōutōng,|dàn fāngyán yě chéngzàizhe|dìfāng wénhuà hé shēnfèn.', 'Mandarin enables people from different regions to communicate|but dialects also carry|local culture and identity', 'Mandarin enables broad communication, while dialects carry local identity.', 'मानक चीनी सबको जोड़ती है, जबकि बोलियाँ स्थानीय संस्कृति और पहचान सँभालती हैं।'),
    U('听到陌生口音时|先抓关键词，|不要急着否定自己。', 'Tīngdào mòshēng kǒuyīn shí|xiān zhuā guānjiàncí,|bú yào jízhe fǒudìng zìjǐ.', 'when hearing an unfamiliar accent|catch key words first|do not doubt yourself immediately', 'With an unfamiliar accent, focus on key words instead of panicking.', 'अनजान लहजे में पहले मुख्य शब्द पकड़ें और घबराएँ नहीं।')),
  T('classical-references', 'reading',
    U('“塞翁失马”这个典故|提醒人们|祸福可能互相转化。', '“Sàiwēngshīmǎ” zhège diǎngù|tíxǐng rénmen|huòfú kěnéng hùxiāng zhuǎnhuà.', 'the allusion the old frontier man lost his horse|reminds people|misfortune and fortune may transform', 'The allusion 塞翁失马 reminds us that fortune and misfortune can change.', '“塞翁失马” बताता है कि दुर्भाग्य और सौभाग्य एक-दूसरे में बदल सकते हैं।'),
    U('理解典故来源|能帮助你|读懂现代文章中的暗示。', 'Lǐjiě diǎngù láiyuán|néng bāngzhù nǐ|dúdǒng xiàndài wénzhāng zhōng de ànshì.', 'understanding an allusion’s origin|can help you|understand hints in modern writing', 'Knowing an allusion’s origin helps you understand modern references.', 'प्राचीन संदर्भ का स्रोत जानने से आधुनिक लेखों के संकेत समझ आते हैं।')),
  T('mastery-challenge', 'fluency',
    U('面对陌生话题，|我会先界定问题，|再比较不同观点的依据。', 'Miànduì mòshēng huàtí,|wǒ huì xiān jièdìng wèntí,|zài bǐjiào bùtóng guāndiǎn de yījù.', 'when facing an unfamiliar topic|I first define the question|then compare evidence behind different views', 'With an unfamiliar topic, I define the question before comparing evidence.', 'अनजान विषय में मैं पहले प्रश्न तय करता/करती हूँ, फिर अलग राय के प्रमाण देखता/देखती हूँ।'),
    U('即使一时找不到准确的词，|也能通过解释和举例|把意思说清楚。', 'Jíshǐ yìshí zhǎo bu dào zhǔnquè de cí,|yě néng tōngguò jiěshì hé jǔlì|bǎ yìsi shuō qīngchu.', 'even if the exact word is unavailable for a moment|through explanation and examples one can|make the meaning clear', 'Even without the exact word, explanations and examples can make the idea clear.', 'सही शब्द न मिले तो भी समझाकर और उदाहरण देकर बात स्पष्ट की जा सकती है।')),
  T('the-fluent-speaker', 'fluency',
    U('真正的流利|不是从不犯错，|而是能自然地继续交流。', 'Zhēnzhèng de liúlì|bú shì cóng bù fàncuò,|ér shì néng zìrán de jìxù jiāoliú.', 'true fluency|is not never making mistakes|but continuing communication naturally', 'True fluency is not never making mistakes; it is continuing naturally.', 'सच्ची धाराप्रवाहता गलती न करना नहीं, बल्कि स्वाभाविक संवाद जारी रखना है।'),
    U('我会根据对方的反应|调整表达，|让沟通更准确也更有人情味。', 'Wǒ huì gēnjù duìfāng de fǎnyìng|tiáozhěng biǎodá,|ràng gōutōng gèng zhǔnquè yě gèng yǒu rénqíngwèi.', 'based on the listener’s reaction I|adjust my expression|make communication accurate and humane', 'I adapt to the listener so communication stays accurate and human.', 'मैं सामने वाले की प्रतिक्रिया के अनुसार भाषा बदलता/बदलती हूँ ताकि संवाद सटीक और मानवीय रहे।')),
];
